/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/arduino_uno_-_low_poly.glb 
Author: Spark (https://sketchfab.com/muammar.yacoob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arduino-uno-low-poly-43cebeb50dc14ab490b553f0a0077eb9
Title: Arduino UNO - Low Poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/arduino_uno_-_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.005, 5.132, 12.455]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Arduino_Blue2_FiberGlass_0.geometry} material={materials.FiberGlass} />
        <mesh geometry={nodes.Arduino_Blue2_Metal_0.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Arduino_Blue2_Back_0.geometry} material={materials.Back} />
        <mesh geometry={nodes.Arduino_Blue2_LED_0.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/arduino_uno_-_low_poly.glb')
