/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/arduino_breadboard_-_low_poly.glb 
Author: Matys (https://sketchfab.com/Matysino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arduino-breadboard-low-poly-497ee275a25e4166b98c7be3105b4ad9
Title: Arduino Breadboard - Low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/arduino_breadboard_-_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LP_breadboard_0.geometry} material={materials.breadboard} rotation={[-Math.PI / 2, 0, 0]} scale={[812.429, 100, 45.095]} />
    </group>
  )
}

useGLTF.preload('/arduino_breadboard_-_low_poly.glb')
