-- ============================================================================
-- STEM IDEA GENERATOR - COMPLETE DATABASE SCHEMA
-- ============================================================================
-- This is the COMPLETE SQL file to run in Supabase SQL Editor
-- It creates all tables with proper structure and populates with sample data
-- that matches the frontend component interface requirements
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- DROP EXISTING TABLES (Clean slate)
-- ============================================================================
DROP TABLE IF EXISTS public.component_alternatives CASCADE;
DROP TABLE IF EXISTS public.component_projects CASCADE;
DROP TABLE IF EXISTS public.component_reviews CASCADE;
DROP TABLE IF EXISTS public.chat_messages CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.components CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Drop existing functions
DROP FUNCTION IF EXISTS get_component_details(UUID);
DROP FUNCTION IF EXISTS get_user_projects(VARCHAR);
DROP FUNCTION IF EXISTS get_project_chat_history(UUID, INTEGER);
DROP FUNCTION IF EXISTS update_updated_at_column();

-- ============================================================================
-- TABLE: users
-- Guest users with randomly generated IDs (no authentication required)
-- ============================================================================
CREATE TABLE public.users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    guest_id VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    preferences JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}'
);

-- ============================================================================
-- TABLE: components
-- Electronics components with detailed specifications
-- NOTE: price is stored as VARCHAR to include currency symbol formatting
-- NOTE: stock is stored as VARCHAR ('In Stock', 'Out of Stock', 'Limited')
-- ============================================================================
CREATE TABLE public.components (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT,
    price VARCHAR(50),
    stock VARCHAR(50) DEFAULT 'In Stock',
    stock_count INTEGER DEFAULT 0,
    manufacturer VARCHAR(255),
    model_number VARCHAR(100),
    datasheet_url TEXT,
    image_url TEXT,
    specifications JSONB DEFAULT '{}',
    tags TEXT[] DEFAULT '{}',
    dimensions JSONB DEFAULT '{}',
    weight DECIMAL(8,3),
    operating_voltage_min DECIMAL(5,2),
    operating_voltage_max DECIMAL(5,2),
    operating_current DECIMAL(8,3),
    power_consumption DECIMAL(8,3),
    interface_type VARCHAR(100),
    pin_count INTEGER,
    package_type VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: projects
-- User's saved project ideas (generated by AI)
-- ============================================================================
CREATE TABLE public.projects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    difficulty VARCHAR(50),
    estimated_time VARCHAR(100),
    estimated_cost VARCHAR(100),
    components TEXT[] DEFAULT '{}',
    skills TEXT[] DEFAULT '{}',
    steps TEXT[] DEFAULT '{}',
    status VARCHAR(50) DEFAULT 'planning',
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    notes TEXT DEFAULT '',
    starred BOOLEAN DEFAULT false,
    tags TEXT[] DEFAULT '{}',
    completed_steps INTEGER[] DEFAULT '{}',
    generated_from_params JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: chat_messages
-- AI guidance chat messages for each project
-- ============================================================================
CREATE TABLE public.chat_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    session_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(50) DEFAULT 'text',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: component_reviews
-- User reviews and ratings for components
-- ============================================================================
CREATE TABLE public.component_reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    component_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    user_name VARCHAR(255),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    pros TEXT[],
    cons TEXT[],
    use_case TEXT,
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: component_projects
-- Example projects using components
-- ============================================================================
CREATE TABLE public.component_projects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    component_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    project_name VARCHAR(255) NOT NULL,
    project_description TEXT,
    project_url TEXT,
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    estimated_time VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: component_alternatives
-- Alternative/similar components
-- ============================================================================
CREATE TABLE public.component_alternatives (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    component_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    alternative_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    reason TEXT,
    compatibility_score INTEGER CHECK (compatibility_score >= 1 AND compatibility_score <= 10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- INDEXES for performance optimization
-- ============================================================================
CREATE INDEX idx_users_guest_id ON public.users(guest_id);
CREATE INDEX idx_users_last_active ON public.users(last_active);

CREATE INDEX idx_components_category ON public.components(category);
CREATE INDEX idx_components_name ON public.components(name);
CREATE INDEX idx_components_stock ON public.components(stock);
CREATE INDEX idx_components_tags ON public.components USING GIN(tags);

CREATE INDEX idx_projects_user_id ON public.projects(user_id);
CREATE INDEX idx_projects_status ON public.projects(status);
CREATE INDEX idx_projects_starred ON public.projects(starred);
CREATE INDEX idx_projects_created_at ON public.projects(created_at DESC);

CREATE INDEX idx_chat_messages_project_id ON public.chat_messages(project_id);
CREATE INDEX idx_chat_messages_user_id ON public.chat_messages(user_id);
CREATE INDEX idx_chat_messages_session_id ON public.chat_messages(session_id);
CREATE INDEX idx_chat_messages_created_at ON public.chat_messages(created_at DESC);

CREATE INDEX idx_component_reviews_component_id ON public.component_reviews(component_id);
CREATE INDEX idx_component_reviews_rating ON public.component_reviews(rating);

-- ============================================================================
-- TRIGGERS for automatic timestamp updates
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_components_updated_at 
    BEFORE UPDATE ON public.components 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at 
    BEFORE UPDATE ON public.projects 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) Policies
-- ============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_alternatives ENABLE ROW LEVEL SECURITY;

-- Allow all operations for guest users
CREATE POLICY "Allow all on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on components" ON public.components FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on chat_messages" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on component_reviews" ON public.component_reviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on component_projects" ON public.component_projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on component_alternatives" ON public.component_alternatives FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- INSERT COMPONENTS - Electronics Components with proper stock and price format
-- ============================================================================

-- MICROCONTROLLERS (20 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('Arduino Uno R3', 'Microcontrollers', 'Popular microcontroller board based on ATmega328P, perfect for beginners and prototyping projects', '$25.00', 'In Stock', 150, 'Arduino', 'A000066', '{"clock_speed": "16 MHz", "flash_memory": "32 KB", "sram": "2 KB", "eeprom": "1 KB", "digital_io_pins": "14", "analog_input_pins": "6", "pwm_pins": "6"}', ARRAY['arduino', 'microcontroller', 'beginner', 'popular', 'atmega328p'], '{"width": 68.6, "height": 53.4, "depth": 15, "unit": "mm"}', 7.0, 12.0, 50.0, 'USB/Serial', 30, 'DIP'),

('Arduino Mega 2560', 'Microcontrollers', 'High-capacity Arduino board with more I/O pins and memory for complex projects', '$45.00', 'In Stock', 75, 'Arduino', 'A000067', '{"clock_speed": "16 MHz", "flash_memory": "256 KB", "sram": "8 KB", "eeprom": "4 KB", "digital_io_pins": "54", "analog_input_pins": "16", "pwm_pins": "15"}', ARRAY['arduino', 'microcontroller', 'advanced', 'atmega2560', 'high-capacity'], '{"width": 101.52, "height": 53.3, "depth": 15, "unit": "mm"}', 7.0, 12.0, 80.0, 'USB/Serial', 86, 'DIP'),

('Arduino Nano', 'Microcontrollers', 'Compact Arduino board ideal for breadboard projects and space-constrained applications', '$15.00', 'In Stock', 200, 'Arduino', 'A000005', '{"clock_speed": "16 MHz", "flash_memory": "32 KB", "sram": "2 KB", "eeprom": "1 KB", "digital_io_pins": "14", "analog_input_pins": "8", "pwm_pins": "6"}', ARRAY['arduino', 'microcontroller', 'compact', 'breadboard', 'atmega328p'], '{"width": 18, "height": 45, "depth": 15, "unit": "mm"}', 7.0, 12.0, 40.0, 'USB/Serial', 30, 'DIP'),

('ESP32 DevKit V1', 'Microcontrollers', 'Powerful WiFi and Bluetooth enabled microcontroller for IoT projects', '$12.00', 'In Stock', 120, 'Espressif', 'ESP32-WROOM-32', '{"clock_speed": "240 MHz", "flash_memory": "4 MB", "sram": "520 KB", "wifi": "802.11 b/g/n", "bluetooth": "4.2", "digital_io_pins": "34", "analog_input_pins": "18", "pwm_pins": "16"}', ARRAY['esp32', 'wifi', 'bluetooth', 'iot', 'wireless', 'dual-core'], '{"width": 25.4, "height": 55, "depth": 15, "unit": "mm"}', 3.0, 3.6, 160.0, 'WiFi/Bluetooth/SPI/I2C', 38, 'Module'),

('ESP8266 NodeMCU', 'Microcontrollers', 'WiFi development board based on ESP8266 with built-in USB and breadboard-friendly design', '$8.00', 'In Stock', 150, 'Espressif', 'ESP8266-12E', '{"clock_speed": "80 MHz", "flash_memory": "4 MB", "sram": "128 KB", "wifi": "802.11 b/g/n", "digital_io_pins": "17", "analog_input_pins": "1", "pwm_pins": "17"}', ARRAY['esp8266', 'nodemcu', 'wifi', 'iot', 'development-board'], '{"width": 25.4, "height": 48.26, "depth": 12, "unit": "mm"}', 3.3, 3.3, 80.0, 'WiFi/SPI/I2C/UART', 30, 'Development Board'),

('Raspberry Pi 4 Model B', 'Single Board Computers', 'Powerful single-board computer with quad-core ARM processor, perfect for advanced projects', '$75.00', 'Limited', 50, 'Raspberry Pi Foundation', 'RPI4-MODBP-4GB', '{"processor": "Quad-core ARM Cortex-A72", "clock_speed": "1.5 GHz", "ram": "4 GB", "storage": "microSD", "usb_ports": "4x USB 3.0", "ethernet": "Gigabit", "wifi": "802.11ac", "bluetooth": "5.0"}', ARRAY['raspberry-pi', 'linux', 'sbc', 'advanced', 'quad-core', 'wifi'], '{"width": 85, "height": 56, "depth": 17, "unit": "mm"}', 5.0, 5.0, 1200.0, 'GPIO/USB/Ethernet/WiFi', 40, 'SBC'),

('Raspberry Pi Pico', 'Microcontrollers', 'Low-cost microcontroller board with RP2040 dual-core processor', '$4.00', 'In Stock', 300, 'Raspberry Pi Foundation', 'SC0915', '{"clock_speed": "133 MHz", "flash_memory": "2 MB", "sram": "264 KB", "digital_io_pins": "26", "analog_input_pins": "3", "pwm_pins": "16"}', ARRAY['raspberry-pi', 'pico', 'rp2040', 'micropython'], '{"width": 21, "height": 51, "depth": 4, "unit": "mm"}', 1.8, 5.5, 30.0, 'SPI/I2C/UART', 40, 'Module'),

('STM32 Blue Pill', 'Microcontrollers', 'ARM Cortex-M3 development board with excellent performance', '$6.00', 'In Stock', 100, 'STMicroelectronics', 'STM32F103C8T6', '{"clock_speed": "72 MHz", "flash_memory": "64 KB", "sram": "20 KB", "digital_io_pins": "32", "analog_input_pins": "10"}', ARRAY['stm32', 'arm', 'cortex-m3', '32-bit'], '{"width": 22.9, "height": 53.3, "depth": 5, "unit": "mm"}', 2.0, 3.6, 50.0, 'SPI/I2C/UART', 40, 'Module'),

('Teensy 4.0', 'Microcontrollers', 'High-performance ARM Cortex-M7 microcontroller with incredible speed', '$25.00', 'In Stock', 60, 'PJRC', 'TEENSY40', '{"clock_speed": "600 MHz", "flash_memory": "2 MB", "ram": "1024 KB", "digital_io_pins": "40", "analog_input_pins": "14"}', ARRAY['teensy', 'arm', 'fast', 'high-performance'], '{"width": 18, "height": 36, "depth": 5, "unit": "mm"}', 3.3, 5.5, 100.0, 'USB', 40, 'Module'),

('Arduino Pro Mini', 'Microcontrollers', 'Small Arduino compatible board without USB connector', '$10.00', 'In Stock', 150, 'Arduino', 'DEV-11113', '{"clock_speed": "16 MHz", "flash_memory": "32 KB", "sram": "2 KB", "digital_io_pins": "14", "analog_input_pins": "6"}', ARRAY['arduino', 'mini', 'compact', 'pro'], '{"width": 18, "height": 33, "depth": 5, "unit": "mm"}', 3.3, 12.0, 20.0, 'Serial', 20, 'Module'),

('Arduino Leonardo', 'Microcontrollers', 'Arduino with built-in USB communication for HID devices', '$22.00', 'In Stock', 80, 'Arduino', 'A000057', '{"clock_speed": "16 MHz", "flash_memory": "32 KB", "sram": "2.5 KB", "usb": "native HID"}', ARRAY['arduino', 'usb', 'hid', 'keyboard'], '{"width": 68.6, "height": 53.3, "depth": 15, "unit": "mm"}', 7.0, 12.0, 50.0, 'USB', 30, 'DIP'),

('BBC micro:bit', 'Educational', 'Pocket-sized programmable computer for education with LED matrix', '$18.00', 'In Stock', 100, 'BBC', 'MICROBIT-V2', '{"display": "5x5 LED matrix", "sensors": "accelerometer, compass, temperature", "radio": "Bluetooth LE", "buttons": "2"}', ARRAY['microbit', 'education', 'beginner', 'led-matrix'], '{"width": 51.6, "height": 42, "depth": 11.5, "unit": "mm"}', 3.0, 3.3, 80.0, 'USB', 25, 'Module'),

('Adafruit Feather M0', 'Microcontrollers', 'Lightweight ARM Cortex M0 board with LiPo charging', '$20.00', 'In Stock', 70, 'Adafruit', 'FEATHER-M0', '{"clock_speed": "48 MHz", "flash_memory": "256 KB", "sram": "32 KB", "lipo_charger": "built-in"}', ARRAY['feather', 'arm', 'lipo', 'portable'], '{"width": 22.9, "height": 50.8, "depth": 7, "unit": "mm"}', 3.3, 6.0, 40.0, 'SPI/I2C', 28, 'Module'),

('Particle Photon', 'IoT Boards', 'WiFi-enabled IoT development board with cloud connectivity', '$19.00', 'In Stock', 90, 'Particle', 'PHOTONH', '{"wifi": "802.11 b/g/n", "cloud": "Particle Cloud integrated", "ota": "Over-the-air updates"}', ARRAY['particle', 'wifi', 'iot', 'cloud'], '{"width": 36, "height": 20, "depth": 5, "unit": "mm"}', 3.3, 5.5, 80.0, 'WiFi', 24, 'Module'),

('Wemos D1 Mini', 'Microcontrollers', 'Compact ESP8266 development board with shields ecosystem', '$5.00', 'In Stock', 200, 'Wemos', 'D1MINI', '{"esp8266": true, "wifi": "802.11 b/g/n", "flash_memory": "4 MB"}', ARRAY['esp8266', 'wifi', 'compact', 'wemos'], '{"width": 25.6, "height": 34.2, "depth": 7, "unit": "mm"}', 3.3, 3.3, 70.0, 'WiFi', 16, 'Module'),

('Arduino MKR WiFi 1010', 'IoT Boards', 'IoT-ready Arduino with WiFi and Bluetooth for secure connectivity', '$32.00', 'In Stock', 60, 'Arduino', 'ABX00023', '{"wifi": "802.11 b/g/n", "bluetooth": "4.2", "crypto_chip": "ATECC508A"}', ARRAY['arduino', 'wifi', 'iot', 'secure'], '{"width": 25, "height": 61.5, "depth": 7, "unit": "mm"}', 3.3, 3.3, 80.0, 'WiFi/BLE', 28, 'Module'),

('Adafruit Circuit Playground', 'Educational', 'All-in-one learning board with 10 NeoPixels and sensors', '$25.00', 'In Stock', 100, 'Adafruit', 'CPX', '{"sensors": "10", "neopixels": "10", "speaker": "built-in", "buttons": "2"}', ARRAY['education', 'sensors', 'neopixel', 'beginner'], '{"width": 50.6, "height": 50.6, "depth": 10, "unit": "mm"}', 3.3, 5.0, 100.0, 'USB', 14, 'Round'),

('ESP32-CAM', 'Camera Modules', 'ESP32 with camera for AI/vision projects and streaming', '$10.00', 'In Stock', 120, 'AI-Thinker', 'ESP32-CAM', '{"camera": "OV2640 2MP", "wifi": "802.11 b/g/n", "microsd": "supported"}', ARRAY['esp32', 'camera', 'ai', 'streaming'], '{"width": 27, "height": 40.5, "depth": 12, "unit": "mm"}', 5.0, 5.0, 180.0, 'WiFi', 16, 'Module'),

('LilyPad Arduino', 'Wearables', 'Wearable e-textile technology board for sewable projects', '$15.00', 'In Stock', 50, 'Arduino', 'LILYPAD', '{"sewable": true, "round": true, "lightweight": true}', ARRAY['wearable', 'arduino', 'e-textile', 'sewable'], '{"width": 50, "height": 50, "depth": 3, "unit": "mm"}', 2.7, 5.5, 40.0, 'Serial', 14, 'Round'),

('Pycom WiPy 3.0', 'IoT Boards', 'MicroPython IoT development board with WiFi and Bluetooth', '$28.00', 'In Stock', 40, 'Pycom', 'WIPY3', '{"wifi": "802.11 b/g/n", "bluetooth": "4.2", "micropython": "native support"}', ARRAY['micropython', 'wifi', 'iot', 'pycom'], '{"width": 20.3, "height": 55, "depth": 5, "unit": "mm"}', 3.3, 5.5, 95.0, 'WiFi', 26, 'Module');

-- SENSORS (25 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('DHT22 Temperature Humidity', 'Sensors', 'Digital temperature and humidity sensor with high accuracy', '$8.50', 'In Stock', 300, 'Aosong', 'AM2302', '{"temp_range": "-40 to 80°C", "temp_accuracy": "±0.5°C", "humidity_range": "0-100% RH", "humidity_accuracy": "±2%"}', ARRAY['dht22', 'temperature', 'humidity', 'digital', 'environmental'], '{"width": 14, "height": 18, "depth": 5.5, "unit": "mm"}', 3.3, 6.0, 2.5, 'Digital (One-Wire)', 4, 'Module'),

('HC-SR04 Ultrasonic', 'Sensors', 'Ultrasonic distance sensor for measuring distances from 2cm to 400cm', '$3.50', 'In Stock', 250, 'Generic', 'HC-SR04', '{"range": "2cm to 400cm", "accuracy": "3mm", "measuring_angle": "15°", "frequency": "40 kHz"}', ARRAY['ultrasonic', 'distance', 'sensor', 'ranging'], '{"width": 45, "height": 20, "depth": 15, "unit": "mm"}', 5.0, 5.0, 15.0, 'Digital', 4, 'Module'),

('PIR Motion Sensor', 'Sensors', 'Passive infrared motion detection sensor with adjustable sensitivity', '$3.00', 'In Stock', 200, 'Generic', 'HC-SR501', '{"range": "7 meters", "angle": "110°", "delay": "adjustable 0.3-200s"}', ARRAY['pir', 'motion', 'security', 'infrared'], '{"width": 32, "height": 24, "depth": 25, "unit": "mm"}', 4.5, 20.0, 50.0, 'Digital', 3, 'Module'),

('MPU6050 Gyroscope', 'Sensors', '6-axis gyroscope and accelerometer with digital motion processor', '$5.00', 'In Stock', 180, 'InvenSense', 'MPU6050', '{"axes": "6", "accelerometer_range": "±16g", "gyroscope_range": "±2000°/s", "dmp": "built-in"}', ARRAY['gyroscope', 'accelerometer', 'imu', '6-axis'], '{"width": 20, "height": 16, "depth": 3, "unit": "mm"}', 3.3, 5.0, 3.6, 'I2C', 8, 'Module'),

('BMP280 Pressure Sensor', 'Sensors', 'Barometric pressure and altitude sensor with high precision', '$6.00', 'In Stock', 150, 'Bosch', 'BMP280', '{"pressure_range": "300-1100 hPa", "altitude_accuracy": "±1m", "temperature": "yes"}', ARRAY['pressure', 'altitude', 'barometric', 'weather'], '{"width": 11.6, "height": 11.3, "depth": 3, "unit": "mm"}', 1.8, 3.6, 0.7, 'I2C/SPI', 6, 'Module'),

('DS18B20 Temperature', 'Sensors', 'Digital temperature sensor waterproof probe with 1-Wire interface', '$4.50', 'In Stock', 200, 'Maxim', 'DS18B20', '{"range": "-55 to 125°C", "accuracy": "±0.5°C", "resolution": "12-bit", "waterproof": true}', ARRAY['temperature', 'waterproof', 'one-wire', 'probe'], '{"width": 6, "height": 50, "depth": 6, "unit": "mm"}', 3.0, 5.5, 1.0, 'One-Wire', 3, 'Probe'),

('MQ-2 Gas Sensor', 'Sensors', 'Smoke and flammable gas sensor for safety applications', '$4.00', 'In Stock', 160, 'Hanwei', 'MQ-2', '{"detects": "LPG, propane, methane, smoke", "sensitivity": "200-10000ppm", "preheat": "24h recommended"}', ARRAY['gas', 'smoke', 'safety', 'lpg'], '{"width": 32, "height": 22, "depth": 18, "unit": "mm"}', 5.0, 5.0, 160.0, 'Analog', 4, 'Module'),

('LDR Light Sensor', 'Sensors', 'Light dependent resistor photoresistor for light detection', '$1.00', 'In Stock', 500, 'Generic', 'GL5528', '{"resistance_dark": "1MΩ", "resistance_light": "10kΩ", "response_time": "20ms"}', ARRAY['light', 'photoresistor', 'ldr', 'ambient'], '{"width": 5, "height": 4, "depth": 2, "unit": "mm"}', 3.3, 5.0, 0.1, 'Analog', 2, 'Component'),

('Soil Moisture Sensor', 'Sensors', 'Capacitive soil moisture sensor for plant monitoring', '$3.50', 'In Stock', 180, 'Generic', 'SMS-V2', '{"output": "analog and digital", "type": "capacitive", "corrosion_resistant": true}', ARRAY['soil', 'moisture', 'plants', 'garden'], '{"width": 20, "height": 98, "depth": 5, "unit": "mm"}', 3.3, 5.5, 5.0, 'Analog/Digital', 3, 'Probe'),

('Sound Sensor Module', 'Sensors', 'Microphone sound detection module with adjustable sensitivity', '$2.50', 'In Stock', 220, 'Generic', 'KY-038', '{"sensitivity": "adjustable", "output": "analog/digital", "microphone": "electret condenser"}', ARRAY['sound', 'microphone', 'audio', 'clap'], '{"width": 32, "height": 17, "depth": 10, "unit": "mm"}', 3.3, 5.0, 4.0, 'Analog/Digital', 3, 'Module'),

('Rain Sensor Module', 'Sensors', 'Raindrop detection sensor for weather monitoring', '$2.00', 'In Stock', 150, 'Generic', 'FC-37', '{"output": "analog and digital", "sensitivity": "adjustable"}', ARRAY['rain', 'water', 'weather', 'detection'], '{"width": 40, "height": 16, "depth": 1.5, "unit": "mm"}', 3.3, 5.0, 3.0, 'Analog/Digital', 4, 'Module'),

('TCS3200 Color Sensor', 'Sensors', 'RGB color recognition sensor with frequency output', '$7.00', 'In Stock', 100, 'TAOS', 'TCS3200', '{"output": "frequency", "colors": "RGB + clear", "filters": "red, green, blue, clear"}', ARRAY['color', 'rgb', 'recognition', 'sorting'], '{"width": 30, "height": 30, "depth": 10, "unit": "mm"}', 2.7, 5.5, 10.0, 'Digital', 8, 'Module'),

('Flame Sensor Module', 'Sensors', 'Infrared flame detection sensor for fire safety', '$2.50', 'In Stock', 140, 'Generic', 'KY-026', '{"detection": "760-1100nm", "angle": "60°", "range": "100cm"}', ARRAY['flame', 'fire', 'safety', 'infrared'], '{"width": 32, "height": 14, "depth": 8, "unit": "mm"}', 3.3, 5.0, 15.0, 'Digital', 3, 'Module'),

('Hall Effect Sensor', 'Sensors', 'Magnetic field sensor module for position detection', '$2.00', 'In Stock', 180, 'Allegro', 'A3144', '{"type": "digital latching", "magnetic_field": "switch type", "sensitivity": "high"}', ARRAY['magnetic', 'hall', 'position', 'rpm'], '{"width": 18.5, "height": 15, "depth": 6, "unit": "mm"}', 3.0, 24.0, 9.0, 'Digital', 3, 'Module'),

('Vibration Sensor', 'Sensors', 'SW-420 vibration detection module with adjustable threshold', '$1.50', 'In Stock', 200, 'Generic', 'SW-420', '{"sensitivity": "adjustable", "output": "digital", "indicator": "LED"}', ARRAY['vibration', 'shock', 'knock', 'motion'], '{"width": 30, "height": 12, "depth": 8, "unit": "mm"}', 3.3, 5.0, 3.0, 'Digital', 3, 'Module'),

('IR Obstacle Sensor', 'Sensors', 'Infrared obstacle detection sensor for robotics', '$2.00', 'In Stock', 220, 'Generic', 'FC-51', '{"range": "2-30cm", "output": "digital", "adjustable": true}', ARRAY['infrared', 'obstacle', 'robotics', 'avoidance'], '{"width": 28, "height": 23, "depth": 8, "unit": "mm"}', 3.3, 5.0, 20.0, 'Digital', 3, 'Module'),

('Touch Sensor TTP223', 'Sensors', 'Capacitive touch sensor module with toggle/momentary modes', '$1.50', 'In Stock', 250, 'Generic', 'TTP223', '{"type": "capacitive", "mode": "toggle/momentary", "sensitivity": "adjustable"}', ARRAY['touch', 'capacitive', 'button', 'interface'], '{"width": 24, "height": 24, "depth": 3, "unit": "mm"}', 2.0, 5.5, 1.5, 'Digital', 3, 'Module'),

('GPS Module NEO-6M', 'Sensors', 'GPS positioning satellite receiver with antenna', '$15.00', 'In Stock', 80, 'u-blox', 'NEO-6M', '{"channels": "50", "update_rate": "5Hz", "accuracy": "2.5m CEP", "antenna": "included"}', ARRAY['gps', 'location', 'navigation', 'tracking'], '{"width": 25, "height": 35, "depth": 8, "unit": "mm"}', 3.3, 5.0, 45.0, 'Serial', 4, 'Module'),

('BME680 Environment', 'Sensors', '4-in-1 sensor: temperature, humidity, pressure, and gas (air quality)', '$22.00', 'In Stock', 60, 'Bosch', 'BME680', '{"sensors": "4-in-1", "air_quality": "IAQ index", "gas_sensor": "VOC detection"}', ARRAY['environment', 'air-quality', 'temperature', 'humidity', 'pressure'], '{"width": 18, "height": 11, "depth": 3, "unit": "mm"}', 1.8, 3.6, 0.35, 'I2C/SPI', 8, 'Module'),

('MAX30102 Heart Rate', 'Sensors', 'Pulse oximeter and heart rate sensor for health monitoring', '$12.00', 'In Stock', 90, 'Maxim', 'MAX30102', '{"heart_rate": "yes", "spo2": "blood oxygen", "leds": "red + IR"}', ARRAY['health', 'heart-rate', 'pulse', 'oximeter'], '{"width": 14, "height": 19, "depth": 3, "unit": "mm"}', 1.8, 5.5, 50.0, 'I2C', 6, 'Module'),

('Load Cell 5kg', 'Sensors', 'Weight measurement load cell with HX711 amplifier', '$8.00', 'In Stock', 100, 'Generic', 'HX711', '{"capacity": "5kg", "accuracy": "±0.1g", "amplifier": "HX711 included"}', ARRAY['weight', 'scale', 'load-cell', 'measurement'], '{"width": 12.7, "height": 80, "depth": 12.7, "unit": "mm"}', 3.3, 5.0, 1.5, 'Digital', 4, 'Sensor'),

('RCWL-0516 Microwave', 'Sensors', 'Microwave radar motion sensor with through-wall detection', '$3.00', 'In Stock', 120, 'Generic', 'RCWL-0516', '{"range": "7 meters", "through_wall": "yes", "frequency": "3.18GHz"}', ARRAY['motion', 'radar', 'microwave', 'security'], '{"width": 37, "height": 17, "depth": 5, "unit": "mm"}', 4.0, 28.0, 3.0, 'Digital', 3, 'Module'),

('MLX90614 IR Temperature', 'Sensors', 'Non-contact infrared temperature sensor for contactless measurement', '$12.00', 'In Stock', 70, 'Melexis', 'MLX90614', '{"range": "-70 to 380°C", "contactless": true, "accuracy": "±0.5°C"}', ARRAY['temperature', 'infrared', 'contactless', 'thermal'], '{"width": 15, "height": 8, "depth": 5, "unit": "mm"}', 3.3, 5.0, 2.0, 'I2C', 4, 'Module'),

('VL53L0X Laser Distance', 'Sensors', 'Time-of-flight laser distance sensor with I2C interface', '$14.00', 'In Stock', 80, 'STMicroelectronics', 'VL53L0X', '{"range": "30-2000mm", "accuracy": "±3%", "type": "time-of-flight", "laser": "940nm VCSEL"}', ARRAY['distance', 'laser', 'tof', 'lidar'], '{"width": 16, "height": 16, "depth": 3, "unit": "mm"}', 2.8, 3.6, 10.0, 'I2C', 6, 'Module'),

('ADXL345 Accelerometer', 'Sensors', '3-axis digital accelerometer with programmable ranges', '$8.00', 'In Stock', 110, 'Analog Devices', 'ADXL345', '{"axes": "3", "range": "±2g to ±16g", "resolution": "13-bit", "tap_detection": "yes"}', ARRAY['accelerometer', '3-axis', 'motion', 'tilt'], '{"width": 20, "height": 15, "depth": 3, "unit": "mm"}', 2.0, 3.6, 0.14, 'I2C/SPI', 8, 'Module');

-- DISPLAYS (15 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('16x2 LCD Display', 'Displays', 'Character LCD display with I2C backpack for easy wiring', '$6.00', 'In Stock', 200, 'Generic', 'LCD1602', '{"characters": "16x2", "backlight": "blue/white", "controller": "HD44780", "i2c_module": "PCF8574"}', ARRAY['lcd', 'display', 'character', 'i2c'], '{"width": 80, "height": 36, "depth": 12, "unit": "mm"}', 5.0, 5.0, 50.0, 'I2C', 4, 'Module'),

('0.96 inch OLED Display', 'Displays', 'Small OLED display with I2C interface and high contrast', '$8.00', 'In Stock', 180, 'Generic', 'SSD1306', '{"resolution": "128x64", "color": "white/blue", "controller": "SSD1306", "contrast": "10000:1"}', ARRAY['oled', 'display', 'i2c', 'small'], '{"width": 27, "height": 27, "depth": 4, "unit": "mm"}', 3.3, 5.0, 20.0, 'I2C', 4, 'Module'),

('1.3 inch OLED Display', 'Displays', 'Medium OLED display with SPI/I2C interface options', '$12.00', 'In Stock', 120, 'Generic', 'SH1106', '{"resolution": "128x64", "color": "white", "controller": "SH1106"}', ARRAY['oled', 'display', 'spi', 'i2c'], '{"width": 35, "height": 35, "depth": 4, "unit": "mm"}', 3.3, 5.0, 25.0, 'I2C/SPI', 7, 'Module'),

('MAX7219 LED Matrix', 'Displays', '8x8 LED dot matrix display with cascading support', '$5.00', 'In Stock', 150, 'Maxim', 'MAX7219', '{"size": "8x8", "cascade": "yes", "color": "red", "brightness": "16 levels"}', ARRAY['led', 'matrix', 'dot-matrix', 'scrolling'], '{"width": 32, "height": 32, "depth": 12, "unit": "mm"}', 4.7, 5.3, 320.0, 'SPI', 5, 'Module'),

('TM1637 4-Digit Display', 'Displays', '7-segment LED display with 4 digits and colon', '$3.00', 'In Stock', 200, 'Titan Micro', 'TM1637', '{"digits": "4", "color": "red", "brightness": "8 levels", "colon": "yes"}', ARRAY['7-segment', 'display', 'clock', 'counter'], '{"width": 30, "height": 14, "depth": 5, "unit": "mm"}', 3.3, 5.5, 80.0, 'Digital', 4, 'Module'),

('2.4 inch TFT LCD Display', 'Displays', 'Color TFT LCD touchscreen for graphical interfaces', '$18.00', 'In Stock', 90, 'Generic', 'ILI9341', '{"resolution": "240x320", "colors": "65K", "touchscreen": "resistive", "controller": "ILI9341"}', ARRAY['tft', 'lcd', 'touch', 'color'], '{"width": 50, "height": 86, "depth": 8, "unit": "mm"}', 3.3, 5.0, 100.0, 'SPI', 14, 'Module'),

('Nokia 5110 LCD', 'Displays', 'Monochrome graphic LCD display with low power consumption', '$5.00', 'In Stock', 140, 'Nokia', 'PCD8544', '{"resolution": "84x48", "monochrome": true, "backlight": "blue", "low_power": true}', ARRAY['lcd', 'nokia', 'monochrome', 'retro'], '{"width": 43, "height": 43, "depth": 8, "unit": "mm"}', 2.7, 3.3, 6.0, 'SPI', 8, 'Module'),

('WS2812B LED Strip', 'Displays', 'Addressable RGB LED strip with individual pixel control', '$12.00', 'In Stock', 150, 'WorldSemi', 'WS2812B', '{"leds_per_meter": "30", "color": "RGB", "addressable": true, "voltage": "5V DC"}', ARRAY['led', 'rgb', 'strip', 'neopixel', 'addressable'], '{"width": 10, "height": 1000, "depth": 2, "unit": "mm"}', 5.0, 5.0, 1800.0, 'Digital', 3, 'Strip'),

('NeoPixel Ring 16', 'Displays', '16-LED NeoPixel ring for circular lighting effects', '$10.00', 'In Stock', 100, 'Adafruit', 'WS2812', '{"leds": "16", "color": "RGB", "addressable": true, "ring": true}', ARRAY['neopixel', 'led', 'ring', 'rgb'], '{"width": 44, "height": 44, "depth": 3, "unit": "mm"}', 5.0, 5.0, 960.0, 'Digital', 3, 'Ring'),

('7-Segment Display 1-Digit', 'Displays', 'Single digit 7-segment LED display', '$1.50', 'In Stock', 300, 'Generic', '5161AS', '{"digits": "1", "color": "red", "type": "common cathode", "size": "0.56 inch"}', ARRAY['7-segment', 'led', 'digit', 'basic'], '{"width": 14, "height": 20, "depth": 8, "unit": "mm"}', 5.0, 5.0, 20.0, 'Direct', 10, 'Component'),

('128x32 OLED Display', 'Displays', 'Wide format OLED display for status indicators', '$10.00', 'In Stock', 100, 'Generic', 'SSD1306', '{"resolution": "128x32", "color": "white", "controller": "SSD1306", "wide": true}', ARRAY['oled', 'display', 'wide', 'status'], '{"width": 58, "height": 22, "depth": 4, "unit": "mm"}', 3.3, 5.0, 15.0, 'I2C', 4, 'Module'),

('E-Paper Display 2.9 inch', 'Displays', 'E-ink electronic paper display for low power applications', '$25.00', 'Limited', 50, 'Waveshare', 'EPD-2.9', '{"resolution": "296x128", "color": "black/white", "refresh": "2s full", "low_power": "zero standby"}', ARRAY['e-paper', 'e-ink', 'low-power', 'display'], '{"width": 89, "height": 38, "depth": 3, "unit": "mm"}', 3.3, 5.0, 26.4, 'SPI', 8, 'Module'),

('TFT Display 1.8 inch', 'Displays', 'Compact color TFT LCD with SD card slot', '$12.00', 'In Stock', 80, 'Generic', 'ST7735', '{"resolution": "128x160", "colors": "65K", "sd_card": "yes", "controller": "ST7735"}', ARRAY['tft', 'lcd', 'sd-card', 'compact'], '{"width": 56, "height": 64, "depth": 6, "unit": "mm"}', 3.3, 5.0, 80.0, 'SPI', 10, 'Module'),

('Nixie Tube Clock Kit', 'Displays', 'Vintage nixie tube display for retro clock projects', '$45.00', 'Out of Stock', 0, 'Generic', 'IN-12', '{"tubes": "6", "voltage": "170V", "style": "vintage", "power_supply": "included"}', ARRAY['nixie', 'vintage', 'retro', 'clock'], '{"width": 120, "height": 60, "depth": 30, "unit": "mm"}', 5.0, 12.0, 100.0, 'Serial', 8, 'Kit'),

('LED Bar Graph 10-Segment', 'Displays', '10-segment LED bar graph for level indicators', '$2.50', 'In Stock', 200, 'Generic', 'LM3914', '{"segments": "10", "color": "red/green", "driver": "LM3914 compatible"}', ARRAY['led', 'bar-graph', 'level', 'indicator'], '{"width": 25, "height": 10, "depth": 8, "unit": "mm"}', 5.0, 5.0, 100.0, 'Direct', 20, 'Component');

-- MOTOR CONTROLLERS & ACTUATORS (15 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('L298N Motor Driver', 'Motor Controllers', 'Dual H-bridge motor driver for DC and stepper motors', '$6.00', 'In Stock', 180, 'STMicroelectronics', 'L298N', '{"channels": "2", "max_voltage": "46V", "max_current": "2A per channel", "logic_voltage": "5V"}', ARRAY['motor', 'h-bridge', 'l298n', 'robotics'], '{"width": 43, "height": 43, "depth": 27, "unit": "mm"}', 5.0, 35.0, 36.0, 'PWM', 15, 'Module'),

('L293D Motor Shield', 'Motor Controllers', 'Motor shield for Arduino with support for 4 DC motors', '$8.00', 'In Stock', 120, 'Generic', 'L293D', '{"motors": "4 DC or 2 stepper", "servos": "2", "shield": "Arduino compatible"}', ARRAY['motor', 'shield', 'arduino', 'l293d'], '{"width": 69, "height": 53, "depth": 15, "unit": "mm"}', 4.5, 25.0, 600.0, 'PWM', 16, 'Shield'),

('SG90 Micro Servo', 'Actuators', 'Small lightweight servo motor for robotics and RC projects', '$4.50', 'In Stock', 400, 'TowerPro', 'SG90', '{"torque": "1.8 kg⋅cm", "speed": "0.1s/60°", "rotation": "180°", "weight": "9g"}', ARRAY['servo', 'motor', 'sg90', 'robotics', 'micro'], '{"width": 22.2, "height": 11.5, "depth": 31, "unit": "mm"}', 4.8, 6.0, 100.0, 'PWM', 3, 'Motor'),

('MG996R Servo Motor', 'Actuators', 'High-torque digital servo motor with metal gears', '$10.00', 'In Stock', 150, 'TowerPro', 'MG996R', '{"torque": "11 kg⋅cm", "speed": "0.17s/60°", "rotation": "180°", "gears": "metal"}', ARRAY['servo', 'high-torque', 'metal-gear', 'robotics'], '{"width": 40.7, "height": 19.7, "depth": 42.9, "unit": "mm"}', 4.8, 7.2, 900.0, 'PWM', 3, 'Motor'),

('28BYJ-48 Stepper', 'Actuators', '5V stepper motor with ULN2003 driver board', '$5.00', 'In Stock', 200, 'Generic', '28BYJ-48', '{"steps_per_rev": "2048", "voltage": "5V", "driver": "ULN2003 included", "gear_ratio": "1:64"}', ARRAY['stepper', 'motor', 'uln2003', 'geared'], '{"width": 28, "height": 19, "depth": 28, "unit": "mm"}', 5.0, 12.0, 240.0, 'Digital', 5, 'Motor'),

('NEMA 17 Stepper', 'Actuators', 'Bipolar stepper motor popular for 3D printers and CNC', '$18.00', 'In Stock', 100, 'Generic', 'NEMA17', '{"steps_per_rev": "200", "torque": "40 N⋅cm", "current": "1.7A", "shaft": "5mm"}', ARRAY['stepper', 'nema', '3d-printer', 'cnc'], '{"width": 42, "height": 42, "depth": 40, "unit": "mm"}', 12.0, 12.0, 1700.0, 'Bipolar', 4, 'Motor'),

('DC Motor 3-6V', 'Actuators', 'Small DC hobby motor for basic projects', '$2.00', 'In Stock', 300, 'Generic', 'DC-3V', '{"voltage": "3-6V", "rpm": "12000", "shaft": "2mm", "weight": "18g"}', ARRAY['dc-motor', 'hobby', 'basic', 'cheap'], '{"width": 24, "height": 20, "depth": 30, "unit": "mm"}', 3.0, 6.0, 200.0, 'DC', 2, 'Motor'),

('PCA9685 Servo Driver', 'Motor Controllers', '16-channel PWM servo driver with I2C interface', '$10.00', 'In Stock', 90, 'NXP', 'PCA9685', '{"channels": "16", "pwm_resolution": "12-bit", "frequency": "24Hz-1526Hz", "i2c_address": "configurable"}', ARRAY['servo', 'pwm', 'i2c', '16-channel'], '{"width": 62, "height": 25, "depth": 3, "unit": "mm"}', 3.3, 6.0, 50.0, 'I2C', 16, 'Module'),

('DRV8825 Stepper Driver', 'Motor Controllers', 'Stepper motor driver with up to 1/32 microstepping', '$7.00', 'In Stock', 110, 'Texas Instruments', 'DRV8825', '{"microsteps": "1/32", "max_current": "2.5A", "voltage": "8.2-45V", "protection": "overcurrent, overtemperature"}', ARRAY['stepper', 'driver', 'microstepping', '3d-printer'], '{"width": 20, "height": 15, "depth": 10, "unit": "mm"}', 8.2, 45.0, 2500.0, 'Step/Dir', 16, 'Module'),

('A4988 Stepper Driver', 'Motor Controllers', 'Popular stepper driver for RepRap 3D printers', '$5.00', 'In Stock', 130, 'Allegro', 'A4988', '{"microsteps": "1/16", "max_current": "2A", "voltage": "8-35V", "popular": "3D printers"}', ARRAY['stepper', 'driver', '3d-printer', 'reprap'], '{"width": 20, "height": 15, "depth": 10, "unit": "mm"}', 8.0, 35.0, 2000.0, 'Step/Dir', 16, 'Module'),

('Vibration Motor', 'Actuators', 'Small coin vibration motor for haptic feedback', '$1.50', 'In Stock', 250, 'Generic', 'VM-3V', '{"voltage": "3V", "type": "coin", "diameter": "10mm", "vibration": "strong"}', ARRAY['vibration', 'haptic', 'feedback', 'coin'], '{"width": 10, "height": 10, "depth": 3, "unit": "mm"}', 3.0, 3.7, 80.0, 'DC', 2, 'Motor'),

('Solenoid 5V Push-Pull', 'Actuators', 'Push-pull solenoid actuator for locking mechanisms', '$6.00', 'In Stock', 100, 'Generic', 'JF-0530B', '{"force": "2.5N", "stroke": "10mm", "type": "push-pull", "duty_cycle": "100%"}', ARRAY['solenoid', 'actuator', 'lock', 'push-pull'], '{"width": 14.8, "height": 20, "depth": 31, "unit": "mm"}', 5.0, 5.0, 400.0, 'DC', 2, 'Actuator'),

('Relay Module 5V', 'Actuators', 'Single channel relay module for switching high voltage loads', '$2.50', 'In Stock', 200, 'Generic', 'SRD-05VDC', '{"voltage": "5V", "load": "10A 250VAC", "channels": "1", "optocoupler": "isolated"}', ARRAY['relay', 'switch', 'high-voltage', 'isolated'], '{"width": 38, "height": 43, "depth": 17, "unit": "mm"}', 5.0, 5.0, 70.0, 'Digital', 3, 'Module'),

('Electromagnet 12V', 'Actuators', 'Lifting electromagnet for picking up metal objects', '$8.00', 'In Stock', 80, 'Generic', 'EM-12V', '{"force": "25kg", "voltage": "12V", "type": "lifting", "surface": "metal objects"}', ARRAY['electromagnet', 'magnet', 'lifting', 'picking'], '{"width": 27, "height": 21, "depth": 21, "unit": "mm"}', 12.0, 12.0, 500.0, 'DC', 2, 'Magnet'),

('Linear Actuator Mini', 'Actuators', 'Mini linear actuator with 50mm stroke for precise positioning', '$20.00', 'Limited', 50, 'Generic', 'LA-50MM', '{"stroke": "50mm", "force": "10N", "speed": "10mm/s", "gear_ratio": "298:1"}', ARRAY['linear', 'actuator', 'positioning', 'mini'], '{"width": 16, "height": 90, "depth": 16, "unit": "mm"}', 6.0, 12.0, 350.0, 'DC', 2, 'Actuator');

-- COMMUNICATION MODULES (10 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('HC-05 Bluetooth Module', 'Communication', 'Bluetooth 2.0 serial communication module with AT commands', '$7.00', 'In Stock', 180, 'Generic', 'HC-05', '{"version": "Bluetooth 2.0", "range": "10 meters", "baud_rate": "9600-115200", "mode": "master/slave"}', ARRAY['bluetooth', 'serial', 'hc-05', 'wireless'], '{"width": 28, "height": 15, "depth": 2.5, "unit": "mm"}', 3.6, 6.0, 40.0, 'Serial', 6, 'Module'),

('nRF24L01 Wireless', 'Communication', '2.4GHz wireless transceiver with long range option', '$5.00', 'In Stock', 150, 'Nordic', 'nRF24L01', '{"frequency": "2.4GHz", "range": "100 meters", "channels": "126", "data_rate": "250Kbps-2Mbps"}', ARRAY['wireless', 'rf', '2.4ghz', 'transceiver'], '{"width": 29, "height": 15, "depth": 4, "unit": "mm"}', 1.9, 3.6, 13.5, 'SPI', 8, 'Module'),

('SIM800L GSM Module', 'Communication', 'GSM/GPRS cellular module for SMS and calls', '$12.00', 'In Stock', 70, 'SIMCom', 'SIM800L', '{"bands": "quad-band GSM", "gprs": "class 12", "sms": "yes", "voice": "yes"}', ARRAY['gsm', 'cellular', 'gprs', 'sms'], '{"width": 22, "height": 22, "depth": 3, "unit": "mm"}', 3.7, 4.2, 500.0, 'Serial', 12, 'Module'),

('LoRa SX1278 Module', 'Communication', 'Long range LoRa wireless transceiver for IoT', '$15.00', 'In Stock', 90, 'Semtech', 'SX1278', '{"range": "5km+", "frequency": "433/868/915MHz", "sensitivity": "-148dBm", "spread_factor": "6-12"}', ARRAY['lora', 'wireless', 'long-range', 'iot'], '{"width": 16, "height": 16, "depth": 3, "unit": "mm"}', 1.8, 3.7, 120.0, 'SPI', 16, 'Module'),

('ESP-01 WiFi Module', 'Communication', 'Compact ESP8266 WiFi module for adding WiFi to projects', '$3.00', 'In Stock', 200, 'Espressif', 'ESP-01', '{"wifi": "802.11 b/g/n", "gpio": "2", "flash": "1MB", "adapter": "may need 3.3V adapter"}', ARRAY['wifi', 'esp8266', 'compact', 'addon'], '{"width": 14.3, "height": 24.8, "depth": 3, "unit": "mm"}', 3.0, 3.6, 215.0, 'Serial', 8, 'Module'),

('HC-12 Wireless Serial', 'Communication', '433MHz long range serial communication module', '$8.00', 'In Stock', 100, 'Generic', 'HC-12', '{"frequency": "433MHz", "range": "1800m", "channels": "100", "baud_rate": "1200-115200"}', ARRAY['wireless', 'serial', 'long-range', '433mhz'], '{"width": 27.8, "height": 13.2, "depth": 4, "unit": "mm"}', 3.2, 5.5, 100.0, 'Serial', 9, 'Module'),

('RFID RC522', 'Communication', '13.56MHz RFID reader/writer for access control', '$5.00', 'In Stock', 150, 'NXP', 'MFRC522', '{"frequency": "13.56MHz", "protocol": "ISO 14443A", "range": "5cm", "cards": "Mifare 1K/4K"}', ARRAY['rfid', 'nfc', 'access-control', 'reader'], '{"width": 40, "height": 60, "depth": 3, "unit": "mm"}', 2.5, 3.3, 13.0, 'SPI', 8, 'Module'),

('433MHz Transmitter', 'Communication', 'RF transmitter module for remote control projects', '$2.00', 'In Stock', 180, 'Generic', 'FS1000A', '{"frequency": "433MHz", "power": "10mW", "range": "20-200m", "modulation": "ASK"}', ARRAY['rf', 'transmitter', 'remote', '433mhz'], '{"width": 19, "height": 19, "depth": 5, "unit": "mm"}', 3.5, 12.0, 40.0, 'Digital', 3, 'Module'),

('433MHz Receiver', 'Communication', 'RF receiver module paired with transmitter', '$2.00', 'In Stock', 180, 'Generic', 'XY-MK-5V', '{"frequency": "433MHz", "sensitivity": "-105dBm", "data_rate": "4KB/s"}', ARRAY['rf', 'receiver', 'remote', '433mhz'], '{"width": 30, "height": 14, "depth": 5, "unit": "mm"}', 5.0, 5.0, 4.0, 'Digital', 4, 'Module'),

('IR Transmitter Receiver', 'Communication', 'Infrared transmitter and receiver pair for remote control', '$1.50', 'In Stock', 250, 'Generic', 'IR-LED', '{"wavelength": "940nm", "range": "10 meters", "carrier": "38kHz"}', ARRAY['infrared', 'ir', 'remote', 'tv'], '{"width": 5, "height": 8, "depth": 5, "unit": "mm"}', 3.3, 5.0, 20.0, 'Digital', 2, 'Component');

-- POWER MANAGEMENT (10 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('LM2596 Buck Converter', 'Power Management', 'Adjustable step-down voltage regulator with high efficiency', '$3.50', 'In Stock', 200, 'Texas Instruments', 'LM2596', '{"input": "4-40V", "output": "1.25-37V adjustable", "current": "3A", "efficiency": "up to 92%"}', ARRAY['buck', 'voltage-regulator', 'step-down', 'adjustable'], '{"width": 43, "height": 21, "depth": 14, "unit": "mm"}', 4.0, 40.0, 3000.0, 'DC', 2, 'Module'),

('MT3608 Boost Converter', 'Power Management', 'Step-up voltage regulator for increasing voltage', '$2.50', 'In Stock', 180, 'Generic', 'MT3608', '{"input": "2-24V", "output": "5-28V adjustable", "current": "2A", "type": "boost"}', ARRAY['boost', 'step-up', 'voltage', 'regulator'], '{"width": 37, "height": 17, "depth": 12, "unit": "mm"}', 2.0, 24.0, 2000.0, 'DC', 2, 'Module'),

('AMS1117 3.3V Regulator', 'Power Management', 'Linear voltage regulator fixed 3.3V output', '$1.00', 'In Stock', 300, 'Advanced Monolithic', 'AMS1117', '{"output": "3.3V fixed", "current": "1A", "dropout": "1.3V", "type": "LDO"}', ARRAY['linear', 'regulator', '3.3v', 'ldo'], '{"width": 15, "height": 10, "depth": 3, "unit": "mm"}', 4.75, 15.0, 1000.0, 'DC', 3, 'Component'),

('7805 Voltage Regulator', 'Power Management', 'Classic linear voltage regulator fixed 5V output', '$0.80', 'In Stock', 350, 'Generic', '7805', '{"output": "5V fixed", "current": "1.5A", "dropout": "2V", "package": "TO-220"}', ARRAY['linear', 'regulator', '5v', 'classic'], '{"width": 10, "height": 16, "depth": 5, "unit": "mm"}', 7.0, 35.0, 1500.0, 'DC', 3, 'Component'),

('TP4056 Li-ion Charger', 'Power Management', 'Lithium battery charger module with protection circuit', '$2.00', 'In Stock', 220, 'Generic', 'TP4056', '{"battery": "Li-ion/LiPo", "charge_current": "1A", "protection": "overcharge, overdischarge, short circuit"}', ARRAY['battery', 'charger', 'lithium', 'protection'], '{"width": 26, "height": 17, "depth": 4, "unit": "mm"}', 4.5, 8.0, 1000.0, 'DC', 2, 'Module'),

('18650 Battery Holder', 'Power Management', 'Holder for 18650 lithium battery with leads', '$1.50', 'In Stock', 200, 'Generic', 'BH-18650', '{"batteries": "1", "type": "18650", "leads": "wire", "spring": "yes"}', ARRAY['battery', 'holder', '18650', 'power'], '{"width": 20, "height": 75, "depth": 20, "unit": "mm"}', 3.7, 4.2, 0.0, 'DC', 2, 'Holder'),

('XL6009 Boost Converter', 'Power Management', 'High power adjustable boost converter', '$4.00', 'In Stock', 150, 'Generic', 'XL6009', '{"input": "3-32V", "output": "5-35V adjustable", "current": "4A", "efficiency": "94%"}', ARRAY['boost', 'step-up', 'high-power', 'adjustable'], '{"width": 54, "height": 23, "depth": 14, "unit": "mm"}', 3.0, 32.0, 4000.0, 'DC', 2, 'Module'),

('Power Supply Module 5V', 'Power Management', 'AC-DC isolated power supply module', '$5.00', 'In Stock', 120, 'Generic', 'HLK-PM01', '{"input": "100-240VAC", "output": "5V 2A", "isolated": "yes", "size": "compact"}', ARRAY['power-supply', 'ac-dc', 'isolated', 'mains'], '{"width": 34, "height": 20, "depth": 15, "unit": "mm"}', 100.0, 240.0, 2000.0, 'AC/DC', 3, 'Module'),

('USB Type-C PD Trigger', 'Power Management', 'USB-C power delivery voltage trigger module', '$6.00', 'In Stock', 100, 'Generic', 'PD-USBC', '{"voltage": "5V/9V/12V/15V/20V selectable", "protocol": "PD 3.0", "current": "3A"}', ARRAY['usb-c', 'power-delivery', 'pd', 'trigger'], '{"width": 25, "height": 12, "depth": 5, "unit": "mm"}', 5.0, 20.0, 3000.0, 'USB', 2, 'Module'),

('Solar Panel 6V 1W', 'Power Management', 'Small solar panel for outdoor charging projects', '$8.00', 'In Stock', 90, 'Generic', 'SOLAR-6V-1W', '{"voltage": "6V", "power": "1W", "current": "167mA", "type": "polycrystalline"}', ARRAY['solar', 'renewable', 'charging', 'outdoor'], '{"width": 110, "height": 60, "depth": 3, "unit": "mm"}', 6.0, 6.0, 167.0, 'DC', 2, 'Panel');

-- MISCELLANEOUS (5 items)
INSERT INTO public.components (name, category, description, price, stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('Buzzer 5V Active', 'Audio', 'Active piezo buzzer with built-in oscillator', '$1.00', 'In Stock', 300, 'Generic', 'TMB12A05', '{"frequency": "2300Hz fixed", "sound": "85dB", "type": "active (DC powered)"}', ARRAY['buzzer', 'audio', 'active', 'alarm'], '{"width": 12, "height": 9.5, "depth": 9.5, "unit": "mm"}', 4.0, 8.0, 30.0, 'Digital', 2, 'Component'),

('Passive Buzzer', 'Audio', 'Passive piezo buzzer for generating tones and melodies', '$0.80', 'In Stock', 350, 'Generic', 'PASSIVE-5V', '{"frequency": "variable (PWM)", "sound": "85dB", "type": "passive (needs PWM)"}', ARRAY['buzzer', 'audio', 'passive', 'tone'], '{"width": 12, "height": 9.5, "depth": 9.5, "unit": "mm"}', 3.0, 12.0, 25.0, 'PWM', 2, 'Component'),

('Breadboard 830 Points', 'Prototyping', 'Full-size solderless breadboard for prototyping', '$4.00', 'In Stock', 200, 'Generic', 'BB-830', '{"points": "830 tie points", "size": "full-size", "rails": "2 power rails", "pitch": "0.1 inch"}', ARRAY['breadboard', 'prototyping', 'solderless', 'full-size'], '{"width": 165, "height": 55, "depth": 10, "unit": "mm"}', 0.0, 0.0, 0.0, 'None', 0, 'Board'),

('Jumper Wires Set', 'Prototyping', 'Male-to-male jumper wires 40pcs assorted colors', '$3.00', 'In Stock', 250, 'Generic', 'JW-MM-40', '{"quantity": "40 pcs", "length": "20cm", "type": "male-to-male", "colors": "assorted"}', ARRAY['jumper', 'wires', 'prototyping', 'male-male'], '{"width": 2.54, "height": 200, "depth": 1, "unit": "mm"}', 0.0, 0.0, 0.0, 'None', 0, 'Wire'),

('Real Time Clock DS3231', 'Timing', 'High precision RTC module with temperature compensation', '$5.00', 'In Stock', 130, 'Maxim', 'DS3231', '{"accuracy": "±2ppm", "battery": "CR2032", "interface": "I2C", "temp_compensated": "yes"}', ARRAY['rtc', 'clock', 'time', 'ds3231'], '{"width": 38, "height": 22, "depth": 14, "unit": "mm"}', 2.3, 5.5, 0.2, 'I2C', 6, 'Module');

-- ============================================================================
-- INSERT SAMPLE REVIEWS
-- ============================================================================
INSERT INTO public.component_reviews (component_id, user_name, rating, review_text, pros, cons, use_case, difficulty_level)
SELECT 
    c.id,
    'MakerMike',
    5,
    'Perfect board for beginners! Great documentation and community support makes learning electronics fun.',
    ARRAY['Beginner-friendly', 'Excellent documentation', 'Large community', 'Stable and reliable'],
    ARRAY['Limited memory for complex projects', 'No built-in WiFi'],
    'Learning electronics and programming basics',
    'Beginner'
FROM public.components c WHERE c.name = 'Arduino Uno R3' LIMIT 1;

INSERT INTO public.component_reviews (component_id, user_name, rating, review_text, pros, cons, use_case, difficulty_level)
SELECT 
    c.id,
    'IoTEnthusiast',
    5,
    'Amazing value for money! WiFi and Bluetooth built-in make it perfect for connected IoT projects.',
    ARRAY['Built-in WiFi and Bluetooth', 'Powerful dual-core processor', 'Great for IoT', 'Excellent price'],
    ARRAY['More complex than Arduino for beginners', 'Higher power consumption'],
    'Smart home automation and IoT sensors',
    'Intermediate'
FROM public.components c WHERE c.name = 'ESP32 DevKit V1' LIMIT 1;

INSERT INTO public.component_reviews (component_id, user_name, rating, review_text, pros, cons, use_case, difficulty_level)
SELECT 
    c.id,
    'WeatherStation',
    4,
    'Reliable sensor with good accuracy. The digital interface is much easier to use than analog sensors.',
    ARRAY['High accuracy', 'Digital output', 'Good libraries available', 'Reliable readings'],
    ARRAY['Slower response time than DHT11', 'Needs 2 second minimum sampling interval'],
    'Environmental monitoring and weather stations',
    'Beginner'
FROM public.components c WHERE c.name = 'DHT22 Temperature Humidity' LIMIT 1;

INSERT INTO public.component_reviews (component_id, user_name, rating, review_text, pros, cons, use_case, difficulty_level)
SELECT 
    c.id,
    'RobotBuilder',
    5,
    'Essential component for any robotics project. Easy to interface with Arduino.',
    ARRAY['Simple to use', 'Reliable', 'Good range', 'Affordable'],
    ARRAY['Not very accurate at edges', 'Affected by soft surfaces'],
    'Distance measurement and obstacle avoidance',
    'Beginner'
FROM public.components c WHERE c.name = 'HC-SR04 Ultrasonic' LIMIT 1;

INSERT INTO public.component_reviews (component_id, user_name, rating, review_text, pros, cons, use_case, difficulty_level)
SELECT 
    c.id,
    'LinuxHacker',
    5,
    'Incredible single board computer. Runs full Linux and handles complex tasks easily.',
    ARRAY['Full Linux support', 'Powerful quad-core CPU', '4GB RAM', 'Great connectivity options'],
    ARRAY['Higher price point', 'Requires heatsink for heavy loads', 'Power consumption'],
    'Home server, media center, and complex IoT projects',
    'Advanced'
FROM public.components c WHERE c.name = 'Raspberry Pi 4 Model B' LIMIT 1;

-- ============================================================================
-- INSERT SAMPLE PROJECTS
-- ============================================================================
INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'LED Blink Tutorial', 'Learn the basics of Arduino programming by making an LED blink', 'Beginner', '30 minutes'
FROM public.components c WHERE c.name = 'Arduino Uno R3' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Temperature Logger', 'Build a temperature logging system with SD card storage', 'Intermediate', '2 hours'
FROM public.components c WHERE c.name = 'Arduino Uno R3' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'WiFi Weather Station', 'Create a WiFi-enabled weather station that sends data to the cloud', 'Advanced', '1 week'
FROM public.components c WHERE c.name = 'ESP32 DevKit V1' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Smart Home Controller', 'Build a home automation hub with web interface', 'Advanced', '2 weeks'
FROM public.components c WHERE c.name = 'ESP32 DevKit V1' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Parking Sensor', 'Build an ultrasonic parking distance sensor with LED indicators', 'Intermediate', '3 hours'
FROM public.components c WHERE c.name = 'HC-SR04 Ultrasonic' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Room Occupancy Detector', 'Create a PIR-based room presence detection system', 'Beginner', '1 hour'
FROM public.components c WHERE c.name = 'PIR Motion Sensor' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Robotic Arm', 'Create a simple 3-DOF robotic arm controlled by potentiometers', 'Advanced', '2 weeks'
FROM public.components c WHERE c.name = 'SG90 Micro Servo' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'NeoPixel Mood Lamp', 'Build an ambient lighting system with color effects', 'Intermediate', '4 hours'
FROM public.components c WHERE c.name = 'WS2812B LED Strip' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'Air Quality Monitor', 'Monitor indoor air quality with real-time display', 'Advanced', '1 week'
FROM public.components c WHERE c.name = 'BME680 Environment' LIMIT 1;

INSERT INTO public.component_projects (component_id, project_name, project_description, difficulty_level, estimated_time)
SELECT c.id, 'RFID Door Lock', 'Create a secure door lock system with RFID cards', 'Intermediate', '4 hours'
FROM public.components c WHERE c.name = 'RFID RC522' LIMIT 1;

-- ============================================================================
-- INSERT COMPONENT ALTERNATIVES
-- ============================================================================
INSERT INTO public.component_alternatives (component_id, alternative_id, reason, compatibility_score)
SELECT c1.id, c2.id, 'Smaller form factor with same ATmega328P chip, ideal for space-constrained projects', 9
FROM public.components c1, public.components c2
WHERE c1.name = 'Arduino Uno R3' AND c2.name = 'Arduino Nano' LIMIT 1;

INSERT INTO public.component_alternatives (component_id, alternative_id, reason, compatibility_score)
SELECT c1.id, c2.id, 'More powerful with 54 I/O pins, better for complex projects', 7
FROM public.components c1, public.components c2
WHERE c1.name = 'Arduino Uno R3' AND c2.name = 'Arduino Mega 2560' LIMIT 1;

INSERT INTO public.component_alternatives (component_id, alternative_id, reason, compatibility_score)
SELECT c1.id, c2.id, 'More powerful with Bluetooth support and dual-core processor', 8
FROM public.components c1, public.components c2
WHERE c1.name = 'ESP8266 NodeMCU' AND c2.name = 'ESP32 DevKit V1' LIMIT 1;

INSERT INTO public.component_alternatives (component_id, alternative_id, reason, compatibility_score)
SELECT c1.id, c2.id, 'Lower cost option with basic WiFi functionality', 7
FROM public.components c1, public.components c2
WHERE c1.name = 'ESP32 DevKit V1' AND c2.name = 'ESP8266 NodeMCU' LIMIT 1;

INSERT INTO public.component_alternatives (component_id, alternative_id, reason, compatibility_score)
SELECT c1.id, c2.id, 'Higher torque option with metal gears for heavy loads', 8
FROM public.components c1, public.components c2
WHERE c1.name = 'SG90 Micro Servo' AND c2.name = 'MG996R Servo Motor' LIMIT 1;

-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================
CREATE OR REPLACE FUNCTION get_component_details(component_uuid UUID)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_build_object(
        'component', row_to_json(c),
        'reviews', COALESCE(reviews.reviews, '[]'::json),
        'projects', COALESCE(projects.projects, '[]'::json),
        'alternatives', COALESCE(alternatives.alternatives, '[]'::json),
        'stats', json_build_object(
            'average_rating', COALESCE((SELECT AVG(rating) FROM public.component_reviews WHERE component_id = c.id), 0),
            'review_count', (SELECT COUNT(*) FROM public.component_reviews WHERE component_id = c.id),
            'project_count', (SELECT COUNT(*) FROM public.component_projects WHERE component_id = c.id),
            'alternative_count', (SELECT COUNT(*) FROM public.component_alternatives WHERE component_id = c.id)
        )
    ) INTO result
    FROM public.components c
    LEFT JOIN LATERAL (
        SELECT json_agg(row_to_json(rev)) as reviews
        FROM public.component_reviews rev
        WHERE rev.component_id = c.id
    ) reviews ON true
    LEFT JOIN LATERAL (
        SELECT json_agg(row_to_json(proj)) as projects
        FROM public.component_projects proj
        WHERE proj.component_id = c.id
    ) projects ON true
    LEFT JOIN LATERAL (
        SELECT json_agg(
            json_build_object(
                'id', alt_comp.id,
                'name', alt_comp.name,
                'category', alt_comp.category,
                'reason', alt.reason,
                'compatibility_score', alt.compatibility_score
            )
        ) as alternatives
        FROM public.component_alternatives alt
        JOIN public.components alt_comp ON alt.alternative_id = alt_comp.id
        WHERE alt.component_id = c.id
    ) alternatives ON true
    WHERE c.id = component_uuid;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_user_projects(user_guest_id VARCHAR)
RETURNS JSON AS $$
DECLARE
    result JSON;
    user_uuid UUID;
BEGIN
    SELECT id INTO user_uuid FROM public.users WHERE guest_id = user_guest_id;
    
    IF user_uuid IS NULL THEN
        RETURN '[]'::json;
    END IF;
    
    SELECT json_agg(
        json_build_object(
            'project', row_to_json(p),
            'chat_count', (SELECT COUNT(*) FROM public.chat_messages WHERE project_id = p.id)
        ) ORDER BY p.created_at DESC
    ) INTO result
    FROM public.projects p
    WHERE p.user_id = user_uuid;
    
    RETURN COALESCE(result, '[]'::json);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_project_chat_history(project_uuid UUID, message_limit INTEGER DEFAULT 100)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_agg(row_to_json(cm) ORDER BY cm.created_at ASC) INTO result
    FROM (
        SELECT * FROM public.chat_messages
        WHERE project_id = project_uuid
        ORDER BY created_at DESC
        LIMIT message_limit
    ) cm;
    
    RETURN COALESCE(result, '[]'::json);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

-- ============================================================================
-- COMPLETION MESSAGE
-- ============================================================================
DO $$
DECLARE
    component_count INTEGER;
    review_count INTEGER;
    project_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO component_count FROM public.components;
    SELECT COUNT(*) INTO review_count FROM public.component_reviews;
    SELECT COUNT(*) INTO project_count FROM public.component_projects;
    
    RAISE NOTICE '';
    RAISE NOTICE '╔══════════════════════════════════════════════════════════════════╗';
    RAISE NOTICE '║     STEM IDEA GENERATOR - DATABASE SCHEMA CREATED SUCCESSFULLY   ║';
    RAISE NOTICE '╠══════════════════════════════════════════════════════════════════╣';
    RAISE NOTICE '║ Tables created:                                                  ║';
    RAISE NOTICE '║   ✓ users (guest user management)                               ║';
    RAISE NOTICE '║   ✓ components (% components with specs)                       ║', component_count;
    RAISE NOTICE '║   ✓ projects (AI-generated project ideas)                       ║';
    RAISE NOTICE '║   ✓ chat_messages (AI guidance conversations)                   ║';
    RAISE NOTICE '║   ✓ component_reviews (% reviews)                              ║', review_count;
    RAISE NOTICE '║   ✓ component_projects (% example projects)                    ║', project_count;
    RAISE NOTICE '║   ✓ component_alternatives (similar components)                 ║';
    RAISE NOTICE '╠══════════════════════════════════════════════════════════════════╣';
    RAISE NOTICE '║ Features:                                                        ║';
    RAISE NOTICE '║   ✓ Proper stock field (In Stock/Limited/Out of Stock)         ║';
    RAISE NOTICE '║   ✓ Formatted prices with $ symbol                             ║';
    RAISE NOTICE '║   ✓ Detailed specifications in JSONB                           ║';
    RAISE NOTICE '║   ✓ Tags array for filtering                                   ║';
    RAISE NOTICE '║   ✓ RLS policies for guest access                              ║';
    RAISE NOTICE '║   ✓ Utility functions for component details                    ║';
    RAISE NOTICE '╠══════════════════════════════════════════════════════════════════╣';
    RAISE NOTICE '║ Categories included:                                            ║';
    RAISE NOTICE '║   - Microcontrollers (20)    - Sensors (25)                     ║';
    RAISE NOTICE '║   - Displays (15)            - Motor Controllers (15)           ║';
    RAISE NOTICE '║   - Communication (10)       - Power Management (10)            ║';
    RAISE NOTICE '║   - Audio/Prototyping (5)                                       ║';
    RAISE NOTICE '╚══════════════════════════════════════════════════════════════════╝';
END $$;
