-- ============================================================================
-- STEM IDEA GENERATOR - MASTER SUPABASE DATABASE SCHEMA
-- ============================================================================
-- This schema includes all tables needed for the complete application:
-- 1. Users (guest users with random IDs)
-- 2. Components (100 electronics components)
-- 3. Projects (AI-generated project ideas)
-- 4. Chat Messages (AI guidance conversations)
-- 5. Project Progress (step tracking and progress)
-- ============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLE: users
-- Stores guest users with randomly generated IDs (no authentication required)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    guest_id VARCHAR(255) UNIQUE NOT NULL,  -- Random guest ID stored in browser
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    preferences JSONB DEFAULT '{}',  -- User preferences like theme, etc.
    metadata JSONB DEFAULT '{}'  -- Any additional user data
);

-- ============================================================================
-- TABLE: components
-- Electronics components with detailed specifications
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.components (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    currency VARCHAR(3) DEFAULT 'USD',
    in_stock BOOLEAN DEFAULT true,
    stock_count INTEGER DEFAULT 0,
    manufacturer VARCHAR(255),
    model_number VARCHAR(100),
    datasheet_url TEXT,
    image_url TEXT,
    specifications JSONB DEFAULT '{}',
    tags TEXT[] DEFAULT '{}',
    dimensions JSONB DEFAULT '{}',  -- {width, height, depth, unit}
    weight DECIMAL(8,3),  -- in grams
    operating_voltage_min DECIMAL(5,2),
    operating_voltage_max DECIMAL(5,2),
    operating_current DECIMAL(8,3),  -- in mA
    power_consumption DECIMAL(8,3),  -- in watts
    interface_type VARCHAR(100),  -- I2C, SPI, UART, Digital, Analog, etc.
    pin_count INTEGER,
    package_type VARCHAR(50),  -- DIP, SMD, Module, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: projects
-- User's saved project ideas (generated by AI)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.projects (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    difficulty VARCHAR(50),  -- Beginner, Intermediate, Advanced, Expert
    estimated_time VARCHAR(100),
    estimated_cost VARCHAR(100),
    components TEXT[] DEFAULT '{}',  -- List of component names
    skills TEXT[] DEFAULT '{}',  -- Required skills
    steps TEXT[] DEFAULT '{}',  -- Project steps
    status VARCHAR(50) DEFAULT 'planning',  -- planning, in-progress, completed, abandoned
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    notes TEXT DEFAULT '',
    starred BOOLEAN DEFAULT false,
    tags TEXT[] DEFAULT '{}',
    completed_steps INTEGER[] DEFAULT '{}',  -- Array of completed step indices
    generated_from_params JSONB DEFAULT '{}',  -- Original generation parameters
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: chat_messages
-- AI guidance chat messages for each project
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    session_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,  -- 'user' or 'assistant'
    content TEXT NOT NULL,
    message_type VARCHAR(50) DEFAULT 'text',  -- text, guidance, blocker_help, clarification
    metadata JSONB DEFAULT '{}',  -- Additional message metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: component_reviews (Optional - for future enhancement)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.component_reviews (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    component_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    user_name VARCHAR(255),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    pros TEXT[],
    cons TEXT[],
    use_case TEXT,
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TABLE: component_projects (Optional - linking components to project examples)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.component_projects (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    component_id UUID REFERENCES public.components(id) ON DELETE CASCADE,
    project_name VARCHAR(255) NOT NULL,
    project_description TEXT,
    project_url TEXT,
    difficulty_level VARCHAR(20) CHECK (difficulty_level IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    estimated_time VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- INDEXES for performance optimization
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_users_guest_id ON public.users(guest_id);
CREATE INDEX IF NOT EXISTS idx_users_last_active ON public.users(last_active);

CREATE INDEX IF NOT EXISTS idx_components_category ON public.components(category);
CREATE INDEX IF NOT EXISTS idx_components_name ON public.components(name);
CREATE INDEX IF NOT EXISTS idx_components_in_stock ON public.components(in_stock);
CREATE INDEX IF NOT EXISTS idx_components_price ON public.components(price);

CREATE INDEX IF NOT EXISTS idx_projects_user_id ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_starred ON public.projects(starred);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_project_id ON public.chat_messages(project_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON public.chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON public.chat_messages(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_component_reviews_component_id ON public.component_reviews(component_id);
CREATE INDEX IF NOT EXISTS idx_component_reviews_rating ON public.component_reviews(rating);

-- ============================================================================
-- TRIGGERS for automatic timestamp updates
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_components_updated_at 
    BEFORE UPDATE ON public.components 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at 
    BEFORE UPDATE ON public.projects 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) Policies
-- Since we're using guest users without auth, we'll make data public
-- but you can customize this later if you add authentication
-- ============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_projects ENABLE ROW LEVEL SECURITY;

-- Allow all operations for now (guest users)
CREATE POLICY "Allow all operations on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on components" ON public.components FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on chat_messages" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on component_reviews" ON public.component_reviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on component_projects" ON public.component_projects FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- INSERT 100 COMPONENTS - Electronics Components for STEM Projects
-- ============================================================================

-- MICROCONTROLLERS (20 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('Arduino Uno R3', 'Microcontrollers', 'Popular microcontroller board based on ATmega328P, perfect for beginners', 25.00, 'USD', true, 150, 'Arduino', 'A000066', '{"clock_speed": "16 MHz", "flash_memory": "32 KB", "sram": "2 KB", "eeprom": "1 KB"}', ARRAY['arduino', 'microcontroller', 'beginner'], '{"width": 68.6, "height": 53.4, "unit": "mm"}', 7.0, 12.0, 50.0, 'USB/Serial', 30, 'DIP'),
('Arduino Mega 2560', 'Microcontrollers', 'High-capacity Arduino with 54 digital I/O pins', 45.00, 'USD', true, 75, 'Arduino', 'A000067', '{"clock_speed": "16 MHz", "flash_memory": "256 KB", "digital_pins": "54"}', ARRAY['arduino', 'advanced'], '{"width": 101.5, "height": 53.3, "unit": "mm"}', 7.0, 12.0, 80.0, 'USB/Serial', 86, 'DIP'),
('Arduino Nano', 'Microcontrollers', 'Compact Arduino board for breadboard projects', 15.00, 'USD', true, 200, 'Arduino', 'A000005', '{"clock_speed": "16 MHz", "flash_memory": "32 KB"}', ARRAY['arduino', 'compact'], '{"width": 18, "height": 45, "unit": "mm"}', 7.0, 12.0, 40.0, 'USB/Serial', 30, 'DIP'),
('ESP32 DevKit V1', 'Microcontrollers', 'Powerful WiFi and Bluetooth enabled microcontroller', 12.00, 'USD', true, 120, 'Espressif', 'ESP32-WROOM-32', '{"clock_speed": "240 MHz", "wifi": "802.11 b/g/n", "bluetooth": "4.2"}', ARRAY['esp32', 'wifi', 'iot'], '{"width": 25.4, "height": 55, "unit": "mm"}', 3.0, 3.6, 160.0, 'WiFi/Bluetooth', 38, 'Module'),
('ESP8266 NodeMCU', 'Microcontrollers', 'WiFi development board based on ESP8266', 8.00, 'USD', true, 150, 'Espressif', 'ESP8266-12E', '{"clock_speed": "80 MHz", "wifi": "802.11 b/g/n"}', ARRAY['esp8266', 'wifi', 'iot'], '{"width": 25.4, "height": 48.3, "unit": "mm"}', 3.3, 3.3, 80.0, 'WiFi', 30, 'Module'),
('Raspberry Pi 4 Model B', 'Single Board Computers', 'Powerful SBC with quad-core ARM processor (4GB RAM)', 75.00, 'USD', true, 50, 'Raspberry Pi Foundation', 'RPI4-4GB', '{"processor": "Quad-core ARM", "ram": "4 GB", "wifi": "802.11ac"}', ARRAY['raspberry-pi', 'linux', 'sbc'], '{"width": 85, "height": 56, "unit": "mm"}', 5.0, 5.0, 1200.0, 'GPIO/USB', 40, 'SBC'),
('Raspberry Pi Pico', 'Microcontrollers', 'Low-cost microcontroller board with RP2040', 4.00, 'USD', true, 300, 'Raspberry Pi Foundation', 'SC0915', '{"clock_speed": "133 MHz", "flash": "2 MB"}', ARRAY['raspberry-pi', 'pico'], '{"width": 21, "height": 51, "unit": "mm"}', 1.8, 5.5, 30.0, 'SPI/I2C', 40, 'Module'),
('STM32 Blue Pill', 'Microcontrollers', 'ARM Cortex-M3 development board', 6.00, 'USD', true, 100, 'STMicroelectronics', 'STM32F103C8T6', '{"clock_speed": "72 MHz", "flash": "64 KB"}', ARRAY['stm32', 'arm'], '{"width": 22.9, "height": 53.3, "unit": "mm"}', 2.0, 3.6, 50.0, 'SPI/I2C', 40, 'Module'),
('Teensy 4.0', 'Microcontrollers', 'High-performance ARM microcontroller', 25.00, 'USD', true, 60, 'PJRC', 'TEENSY40', '{"clock_speed": "600 MHz", "ram": "1024 KB"}', ARRAY['teensy', 'arm', 'fast'], '{"width": 18, "height": 36, "unit": "mm"}', 3.3, 5.5, 100.0, 'USB', 40, 'Module'),
('Arduino Pro Mini', 'Microcontrollers', 'Small Arduino compatible board', 10.00, 'USD', true, 150, 'Arduino', 'DEV-11113', '{"clock_speed": "16 MHz", "flash": "32 KB"}', ARRAY['arduino', 'mini'], '{"width": 18, "height": 33, "unit": "mm"}', 3.3, 12.0, 20.0, 'Serial', 20, 'Module'),
('Arduino Leonardo', 'Microcontrollers', 'Arduino with built-in USB communication', 22.00, 'USD', true, 80, 'Arduino', 'A000057', '{"clock_speed": "16 MHz", "usb": "native"}', ARRAY['arduino', 'usb'], '{"width": 68.6, "height": 53.3, "unit": "mm"}', 7.0, 12.0, 50.0, 'USB', 30, 'DIP'),
('BBC micro:bit', 'Educational', 'Pocket-sized programmable computer for education', 18.00, 'USD', true, 100, 'BBC', 'MICROBIT-V2', '{"display": "5x5 LED", "sensors": "accelerometer, compass"}', ARRAY['microbit', 'education'], '{"width": 51.6, "height": 42, "unit": "mm"}', 3.0, 3.3, 80.0, 'USB', 25, 'Module'),
('Adafruit Feather M0', 'Microcontrollers', 'Lightweight ARM Cortex M0 board', 20.00, 'USD', true, 70, 'Adafruit', 'FEATHER-M0', '{"clock_speed": "48 MHz", "flash": "256 KB"}', ARRAY['feather', 'arm'], '{"width": 22.9, "height": 50.8, "unit": "mm"}', 3.3, 6.0, 40.0, 'SPI/I2C', 28, 'Module'),
('Particle Photon', 'IoT Boards', 'WiFi-enabled IoT development board', 19.00, 'USD', true, 90, 'Particle', 'PHOTONH', '{"wifi": "802.11 b/g/n", "cloud": "integrated"}', ARRAY['particle', 'wifi', 'iot'], '{"width": 36, "height": 20, "unit": "mm"}', 3.3, 5.5, 80.0, 'WiFi', 24, 'Module'),
('Wemos D1 Mini', 'Microcontrollers', 'Compact ESP8266 development board', 5.00, 'USD', true, 200, 'Wemos', 'D1MINI', '{"esp8266": true, "wifi": "802.11 b/g/n"}', ARRAY['esp8266', 'wifi', 'compact'], '{"width": 25.6, "height": 34.2, "unit": "mm"}', 3.3, 3.3, 70.0, 'WiFi', 16, 'Module'),
('Arduino MKR WiFi 1010', 'IoT Boards', 'IoT-ready Arduino with WiFi and Bluetooth', 32.00, 'USD', true, 60, 'Arduino', 'ABX00023', '{"wifi": "802.11 b/g/n", "bluetooth": "4.2"}', ARRAY['arduino', 'wifi', 'iot'], '{"width": 25, "height": 61.5, "unit": "mm"}', 3.3, 3.3, 80.0, 'WiFi/BLE', 28, 'Module'),
('Adafruit Circuit Playground', 'Educational', 'All-in-one learning board with sensors', 25.00, 'USD', true, 100, 'Adafruit', 'CPX', '{"sensors": "10", "leds": "10", "speaker": "yes"}', ARRAY['education', 'sensors'], '{"width": 50.6, "height": 50.6, "unit": "mm"}', 3.3, 5.0, 100.0, 'USB', 14, 'Round'),
('ESP32-CAM', 'Camera Modules', 'ESP32 with camera for AI/vision projects', 10.00, 'USD', true, 120, 'AI-Thinker', 'ESP32-CAM', '{"camera": "OV2640", "wifi": "802.11 b/g/n"}', ARRAY['esp32', 'camera', 'ai'], '{"width": 27, "height": 40.5, "unit": "mm"}', 5.0, 5.0, 180.0, 'WiFi', 16, 'Module'),
('LilyPad Arduino', 'Wearables', 'Wearable e-textile technology board', 15.00, 'USD', true, 50, 'Arduino', 'LILYPAD', '{"washable": false, "sewable": true}', ARRAY['wearable', 'arduino'], '{"width": 50, "height": 50, "unit": "mm"}', 2.7, 5.5, 40.0, 'Serial', 14, 'Round'),
('Pycom WiPy 3.0', 'IoT Boards', 'MicroPython IoT development board', 28.00, 'USD', true, 40, 'Pycom', 'WIPY3', '{"wifi": "802.11 b/g/n", "micropython": true}', ARRAY['micropython', 'wifi', 'iot'], '{"width": 20.3, "height": 55, "unit": "mm"}', 3.3, 5.5, 95.0, 'WiFi', 26, 'Module');

-- SENSORS (25 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('DHT22 Temperature Humidity', 'Sensors', 'Digital temperature and humidity sensor', 8.50, 'USD', true, 300, 'Aosong', 'AM2302', '{"temp_range": "-40 to 80°C", "humidity": "0-100%"}', ARRAY['dht22', 'temperature', 'humidity'], '{"width": 14, "height": 18, "unit": "mm"}', 3.3, 6.0, 2.5, 'Digital', 4, 'Module'),
('HC-SR04 Ultrasonic', 'Sensors', 'Ultrasonic distance sensor (2cm-400cm)', 3.50, 'USD', true, 250, 'Generic', 'HC-SR04', '{"range": "2-400cm", "accuracy": "3mm"}', ARRAY['ultrasonic', 'distance'], '{"width": 45, "height": 20, "unit": "mm"}', 5.0, 5.0, 15.0, 'Digital', 4, 'Module'),
('PIR Motion Sensor', 'Sensors', 'Passive infrared motion detection sensor', 3.00, 'USD', true, 200, 'Generic', 'HC-SR501', '{"range": "7 meters", "angle": "110°"}', ARRAY['pir', 'motion'], '{"width": 32, "height": 24, "unit": "mm"}', 4.5, 20.0, 50.0, 'Digital', 3, 'Module'),
('MPU6050 Gyroscope', 'Sensors', '6-axis gyroscope and accelerometer', 5.00, 'USD', true, 180, 'InvenSense', 'MPU6050', '{"axes": "6", "accelerometer": "±16g"}', ARRAY['gyroscope', 'accelerometer'], '{"width": 20, "height": 16, "unit": "mm"}', 3.3, 5.0, 3.6, 'I2C', 8, 'Module'),
('BMP280 Pressure Sensor', 'Sensors', 'Barometric pressure and altitude sensor', 6.00, 'USD', true, 150, 'Bosch', 'BMP280', '{"pressure": "300-1100 hPa", "altitude": "±1m"}', ARRAY['pressure', 'altitude'], '{"width": 11.6, "height": 11.3, "unit": "mm"}', 1.8, 3.6, 0.7, 'I2C/SPI', 6, 'Module'),
('DS18B20 Temperature', 'Sensors', 'Digital temperature sensor waterproof', 4.50, 'USD', true, 200, 'Maxim', 'DS18B20', '{"range": "-55 to 125°C", "accuracy": "±0.5°C"}', ARRAY['temperature', 'waterproof'], '{"width": 6, "height": 50, "unit": "mm"}', 3.0, 5.5, 1.0, 'One-Wire', 3, 'Probe'),
('MQ-2 Gas Sensor', 'Sensors', 'Smoke and flammable gas sensor', 4.00, 'USD', true, 160, 'Hanwei', 'MQ-2', '{"detects": "LPG, propane, methane, smoke"}', ARRAY['gas', 'smoke'], '{"width": 32, "height": 22, "unit": "mm"}', 5.0, 5.0, 160.0, 'Analog', 4, 'Module'),
('LDR Light Sensor', 'Sensors', 'Light dependent resistor photoresistor', 1.00, 'USD', true, 500, 'Generic', 'GL5528', '{"resistance": "200kΩ - 10MΩ"}', ARRAY['light', 'photoresistor'], '{"width": 5, "height": 4, "unit": "mm"}', 3.3, 5.0, 0.1, 'Analog', 2, 'Component'),
('Soil Moisture Sensor', 'Sensors', 'Capacitive soil moisture sensor', 3.50, 'USD', true, 180, 'Generic', 'SMS-V2', '{"output": "analog and digital"}', ARRAY['soil', 'moisture', 'plants'], '{"width": 20, "height": 98, "unit": "mm"}', 3.3, 5.5, 5.0, 'Analog/Digital', 3, 'Probe'),
('Sound Sensor Module', 'Sensors', 'Microphone sound detection module', 2.50, 'USD', true, 220, 'Generic', 'KY-038', '{"sensitivity": "adjustable", "output": "analog/digital"}', ARRAY['sound', 'microphone'], '{"width": 32, "height": 17, "unit": "mm"}', 3.3, 5.0, 4.0, 'Analog/Digital', 3, 'Module'),
('Rain Sensor Module', 'Sensors', 'Raindrop detection sensor', 2.00, 'USD', true, 150, 'Generic', 'FC-37', '{"output": "analog and digital"}', ARRAY['rain', 'water'], '{"width": 40, "height": 16, "unit": "mm"}', 3.3, 5.0, 3.0, 'Analog/Digital', 4, 'Module'),
('TCS3200 Color Sensor', 'Sensors', 'RGB color recognition sensor', 7.00, 'USD', true, 100, 'TAOS', 'TCS3200', '{"output": "frequency", "colors": "RGB"}', ARRAY['color', 'rgb'], '{"width": 30, "height": 30, "unit": "mm"}', 2.7, 5.5, 10.0, 'Digital', 8, 'Module'),
('Flame Sensor Module', 'Sensors', 'Infrared flame detection sensor', 2.50, 'USD', true, 140, 'Generic', 'KY-026', '{"detection": "760-1100nm", "angle": "60°"}', ARRAY['flame', 'fire'], '{"width": 32, "height": 14, "unit": "mm"}', 3.3, 5.0, 15.0, 'Digital', 3, 'Module'),
('Hall Effect Sensor', 'Sensors', 'Magnetic field sensor module', 2.00, 'USD', true, 180, 'Allegro', 'A3144', '{"type": "digital", "magnetic": "switch"}', ARRAY['magnetic', 'hall'], '{"width": 18.5, "height": 15, "unit": "mm"}', 3.0, 24.0, 9.0, 'Digital', 3, 'Module'),
('Vibration Sensor', 'Sensors', 'SW-420 vibration detection module', 1.50, 'USD', true, 200, 'Generic', 'SW-420', '{"sensitivity": "adjustable"}', ARRAY['vibration', 'shock'], '{"width": 30, "height": 12, "unit": "mm"}', 3.3, 5.0, 3.0, 'Digital', 3, 'Module'),
('IR Obstacle Sensor', 'Sensors', 'Infrared obstacle detection sensor', 2.00, 'USD', true, 220, 'Generic', 'FC-51', '{"range": "2-30cm", "output": "digital"}', ARRAY['infrared', 'obstacle'], '{"width": 28, "height": 23, "unit": "mm"}', 3.3, 5.0, 20.0, 'Digital', 3, 'Module'),
('Touch Sensor TTP223', 'Sensors', 'Capacitive touch sensor module', 1.50, 'USD', true, 250, 'Generic', 'TTP223', '{"type": "capacitive", "mode": "toggle/momentary"}', ARRAY['touch', 'capacitive'], '{"width": 24, "height": 24, "unit": "mm"}', 2.0, 5.5, 1.5, 'Digital', 3, 'Module'),
('GPS Module NEO-6M', 'Sensors', 'GPS positioning satellite receiver', 15.00, 'USD', true, 80, 'u-blox', 'NEO-6M', '{"channels": "50", "update": "5Hz"}', ARRAY['gps', 'location'], '{"width": 25, "height": 35, "unit": "mm"}', 3.3, 5.0, 45.0, 'Serial', 4, 'Module'),
('BME680 Environment', 'Sensors', 'Temperature, humidity, pressure, gas sensor', 22.00, 'USD', true, 60, 'Bosch', 'BME680', '{"sensors": "4-in-1", "air_quality": "yes"}', ARRAY['environment', 'air-quality'], '{"width": 18, "height": 11, "unit": "mm"}', 1.8, 3.6, 0.35, 'I2C/SPI', 8, 'Module'),
('MAX30102 Heart Rate', 'Sensors', 'Pulse oximeter heart rate sensor', 12.00, 'USD', true, 90, 'Maxim', 'MAX30102', '{"heart_rate": "yes", "spo2": "yes"}', ARRAY['health', 'heart-rate'], '{"width": 14, "height": 19, "unit": "mm"}', 1.8, 5.5, 50.0, 'I2C', 6, 'Module'),
('Load Cell 5kg', 'Sensors', 'Weight measurement load cell with HX711', 8.00, 'USD', true, 100, 'Generic', 'HX711', '{"capacity": "5kg", "accuracy": "±0.1g"}', ARRAY['weight', 'scale'], '{"width": 12.7, "height": 80, "unit": "mm"}', 3.3, 5.0, 1.5, 'Digital', 4, 'Sensor'),
('RCWL-0516 Microwave', 'Sensors', 'Microwave radar motion sensor', 3.00, 'USD', true, 120, 'Generic', 'RCWL-0516', '{"range": "7 meters", "through_wall": "yes"}', ARRAY['motion', 'radar'], '{"width": 37, "height": 17, "unit": "mm"}', 4.0, 28.0, 3.0, 'Digital', 3, 'Module'),
('MLX90614 IR Temperature', 'Sensors', 'Non-contact infrared temperature sensor', 12.00, 'USD', true, 70, 'Melexis', 'MLX90614', '{"range": "-70 to 380°C", "contactless": true}', ARRAY['temperature', 'infrared'], '{"width": 15, "height": 8, "unit": "mm"}', 3.3, 5.0, 2.0, 'I2C', 4, 'Module'),
('VL53L0X Laser Distance', 'Sensors', 'Time-of-flight laser distance sensor', 14.00, 'USD', true, 80, 'STMicroelectronics', 'VL53L0X', '{"range": "30-2000mm", "accuracy": "±3%"}', ARRAY['distance', 'laser', 'tof'], '{"width": 16, "height": 16, "unit": "mm"}', 2.8, 3.6, 10.0, 'I2C', 6, 'Module'),
('ADXL345 Accelerometer', 'Sensors', '3-axis digital accelerometer', 8.00, 'USD', true, 110, 'Analog Devices', 'ADXL345', '{"axes": "3", "range": "±16g"}', ARRAY['accelerometer', '3-axis'], '{"width": 20, "height": 15, "unit": "mm"}', 2.0, 3.6, 0.14, 'I2C/SPI', 8, 'Module');

-- DISPLAYS (15 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('16x2 LCD Display', 'Displays', 'Character LCD display with I2C module', 6.00, 'USD', true, 200, 'Generic', 'LCD1602', '{"characters": "16x2", "backlight": "blue"}', ARRAY['lcd', 'display'], '{"width": 80, "height": 36, "unit": "mm"}', 5.0, 5.0, 50.0, 'I2C', 4, 'Module'),
('0.96" OLED Display', 'Displays', 'Small OLED display with I2C interface', 8.00, 'USD', true, 180, 'Generic', 'SSD1306', '{"resolution": "128x64", "color": "white"}', ARRAY['oled', 'display'], '{"width": 27, "height": 27, "unit": "mm"}', 3.3, 5.0, 20.0, 'I2C', 4, 'Module'),
('1.3" OLED Display', 'Displays', 'OLED display 128x64 SPI/I2C', 12.00, 'USD', true, 120, 'Generic', 'SH1106', '{"resolution": "128x64", "color": "white"}', ARRAY['oled', 'display'], '{"width": 35, "height": 35, "unit": "mm"}', 3.3, 5.0, 25.0, 'I2C/SPI', 7, 'Module'),
('MAX7219 LED Matrix', 'Displays', '8x8 LED dot matrix display module', 5.00, 'USD', true, 150, 'Maxim', 'MAX7219', '{"size": "8x8", "cascade": "yes"}', ARRAY['led', 'matrix'], '{"width": 32, "height": 32, "unit": "mm"}', 4.7, 5.3, 320.0, 'SPI', 5, 'Module'),
('TM1637 4-Digit Display', 'Displays', '7-segment LED display 4 digits', 3.00, 'USD', true, 200, 'Titan Micro', 'TM1637', '{"digits": "4", "color": "red"}', ARRAY['7-segment', 'display'], '{"width": 30, "height": 14, "unit": "mm"}', 3.3, 5.5, 80.0, 'Digital', 4, 'Module'),
('2.4" TFT LCD Display', 'Displays', 'Color TFT LCD touchscreen', 18.00, 'USD', true, 90, 'Generic', 'ILI9341', '{"resolution": "240x320", "touchscreen": "yes"}', ARRAY['tft', 'lcd', 'touch'], '{"width": 50, "height": 86, "unit": "mm"}', 3.3, 5.0, 100.0, 'SPI', 14, 'Module'),
('Nokia 5110 LCD', 'Displays', 'Monochrome graphic LCD display', 5.00, 'USD', true, 140, 'Nokia', 'PCD8544', '{"resolution": "84x48", "monochrome": true}', ARRAY['lcd', 'nokia'], '{"width": 43, "height": 43, "unit": "mm"}', 2.7, 3.3, 6.0, 'SPI', 8, 'Module'),
('WS2812B LED Strip', 'Displays', 'Addressable RGB LED strip (1 meter)', 12.00, 'USD', true, 150, 'WorldSemi', 'WS2812B', '{"leds": "30/meter", "color": "RGB"}', ARRAY['led', 'rgb', 'strip'], '{"width": 10, "height": 1000, "unit": "mm"}', 5.0, 5.0, 1800.0, 'Digital', 3, 'Strip'),
('NeoPixel Ring 16', 'Displays', '16-LED NeoPixel ring', 10.00, 'USD', true, 100, 'Adafruit', 'WS2812', '{"leds": "16", "color": "RGB"}', ARRAY['neopixel', 'led', 'ring'], '{"width": 44, "height": 44, "unit": "mm"}', 5.0, 5.0, 960.0, 'Digital', 3, 'Ring'),
('7-Segment Display 1-Digit', 'Displays', 'Single digit 7-segment display', 1.50, 'USD', true, 300, 'Generic', '5161AS', '{"digits": "1", "color": "red"}', ARRAY['7-segment'], '{"width": 14, "height": 20, "unit": "mm"}', 5.0, 5.0, 20.0, 'Direct', 10, 'Component'),
('128x32 OLED Display', 'Displays', 'Small OLED display I2C', 10.00, 'USD', true, 100, 'Generic', 'SSD1306', '{"resolution": "128x32", "color": "white"}', ARRAY['oled', 'display'], '{"width": 58, "height": 22, "unit": "mm"}', 3.3, 5.0, 15.0, 'I2C', 4, 'Module'),
('E-Paper Display 2.9"', 'Displays', 'E-ink electronic paper display', 25.00, 'USD', true, 50, 'Waveshare', 'EPD-2.9', '{"resolution": "296x128", "color": "black/white"}', ARRAY['e-paper', 'e-ink'], '{"width": 89, "height": 38, "unit": "mm"}', 3.3, 5.0, 26.4, 'SPI', 8, 'Module'),
('TFT Display 1.8"', 'Displays', 'Color TFT LCD with SD card slot', 12.00, 'USD', true, 80, 'Generic', 'ST7735', '{"resolution": "128x160", "sd_card": "yes"}', ARRAY['tft', 'lcd', 'sd'], '{"width": 56, "height": 64, "unit": "mm"}', 3.3, 5.0, 80.0, 'SPI', 10, 'Module'),
('Nixie Tube Clock Kit', 'Displays', 'Vintage nixie tube display', 45.00, 'USD', true, 30, 'Generic', 'IN-12', '{"tubes": "6", "voltage": "170V"}', ARRAY['nixie', 'vintage'], '{"width": 120, "height": 60, "unit": "mm"}', 5.0, 12.0, 100.0, 'Serial', 8, 'Kit'),
('LED Bar Graph 10-Segment', 'Displays', '10-segment LED bar graph', 2.50, 'USD', true, 200, 'Generic', 'LM3914', '{"segments": "10", "color": "red/green"}', ARRAY['led', 'bar-graph'], '{"width": 25, "height": 10, "unit": "mm"}', 5.0, 5.0, 100.0, 'Direct', 20, 'Component');

-- MOTOR CONTROLLERS & ACTUATORS (15 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('L298N Motor Driver', 'Motor Controllers', 'Dual H-bridge motor driver', 6.00, 'USD', true, 180, 'STMicroelectronics', 'L298N', '{"channels": "2", "max_voltage": "46V", "max_current": "2A"}', ARRAY['motor', 'h-bridge'], '{"width": 43, "height": 43, "unit": "mm"}', 5.0, 35.0, 36.0, 'PWM', 15, 'Module'),
('L293D Motor Shield', 'Motor Controllers', 'Motor shield for Arduino with L293D', 8.00, 'USD', true, 120, 'Generic', 'L293D', '{"motors": "4 DC or 2 stepper", "servos": "2"}', ARRAY['motor', 'shield'], '{"width": 69, "height": 53, "unit": "mm"}', 4.5, 25.0, 600.0, 'PWM', 16, 'Shield'),
('SG90 Micro Servo', 'Actuators', 'Small lightweight servo motor', 4.50, 'USD', true, 400, 'TowerPro', 'SG90', '{"torque": "1.8 kg⋅cm", "rotation": "180°"}', ARRAY['servo', 'motor'], '{"width": 22.2, "height": 11.5, "unit": "mm"}', 4.8, 6.0, 100.0, 'PWM', 3, 'Motor'),
('MG996R Servo Motor', 'Actuators', 'High-torque digital servo motor', 10.00, 'USD', true, 150, 'TowerPro', 'MG996R', '{"torque": "11 kg⋅cm", "rotation": "180°"}', ARRAY['servo', 'high-torque'], '{"width": 40.7, "height": 19.7, "unit": "mm"}', 4.8, 7.2, 900.0, 'PWM', 3, 'Motor'),
('28BYJ-48 Stepper', 'Actuators', '5V stepper motor with ULN2003 driver', 5.00, 'USD', true, 200, 'Generic', '28BYJ-48', '{"steps": "2048", "voltage": "5V"}', ARRAY['stepper', 'motor'], '{"width": 28, "height": 19, "unit": "mm"}', 5.0, 12.0, 240.0, 'Digital', 5, 'Motor'),
('NEMA 17 Stepper', 'Actuators', 'Bipolar stepper motor for 3D printers', 18.00, 'USD', true, 100, 'Generic', 'NEMA17', '{"steps": "200", "torque": "40 N⋅cm"}', ARRAY['stepper', 'nema', '3d-printer'], '{"width": 42, "height": 42, "unit": "mm"}', 12.0, 12.0, 1700.0, 'Bipolar', 4, 'Motor'),
('DC Motor 3-6V', 'Actuators', 'Small DC hobby motor', 2.00, 'USD', true, 300, 'Generic', 'DC-3V', '{"voltage": "3-6V", "rpm": "12000"}', ARRAY['dc-motor', 'hobby'], '{"width": 24, "height": 20, "unit": "mm"}', 3.0, 6.0, 200.0, 'DC', 2, 'Motor'),
('PCA9685 Servo Driver', 'Motor Controllers', '16-channel PWM servo driver', 10.00, 'USD', true, 90, 'NXP', 'PCA9685', '{"channels": "16", "pwm": "12-bit"}', ARRAY['servo', 'pwm', 'i2c'], '{"width": 62, "height": 25, "unit": "mm"}', 3.3, 6.0, 50.0, 'I2C', 16, 'Module'),
('DRV8825 Stepper Driver', 'Motor Controllers', 'Stepper motor driver with microstepping', 7.00, 'USD', true, 110, 'Texas Instruments', 'DRV8825', '{"microsteps": "1/32", "current": "2.5A"}', ARRAY['stepper', 'driver'], '{"width": 20, "height": 15, "unit": "mm"}', 8.2, 45.0, 2500.0, 'Step/Dir', 16, 'Module'),
('A4988 Stepper Driver', 'Motor Controllers', 'Stepper driver for 3D printers', 5.00, 'USD', true, 130, 'Allegro', 'A4988', '{"microsteps": "1/16", "current": "2A"}', ARRAY['stepper', 'driver', '3d-printer'], '{"width": 20, "height": 15, "unit": "mm"}', 8.0, 35.0, 2000.0, 'Step/Dir', 16, 'Module'),
('Vibration Motor', 'Actuators', 'Small vibration motor for haptic feedback', 1.50, 'USD', true, 250, 'Generic', 'VM-3V', '{"voltage": "3V", "type": "coin"}', ARRAY['vibration', 'haptic'], '{"width": 10, "height": 3, "unit": "mm"}', 3.0, 3.7, 80.0, 'DC', 2, 'Motor'),
('Solenoid 5V Push-Pull', 'Actuators', 'Push-pull solenoid actuator', 6.00, 'USD', true, 100, 'Generic', 'JF-0530B', '{"force": "2.5N", "stroke": "10mm"}', ARRAY['solenoid', 'actuator'], '{"width": 14.8, "height": 20, "unit": "mm"}', 5.0, 5.0, 400.0, 'DC', 2, 'Actuator'),
('Relay Module 5V', 'Actuators', 'Single channel relay module', 2.50, 'USD', true, 200, 'Generic', 'SRD-05VDC', '{"voltage": "5V", "load": "10A 250VAC"}', ARRAY['relay', 'switch'], '{"width": 38, "height": 43, "unit": "mm"}', 5.0, 5.0, 70.0, 'Digital', 3, 'Module'),
('Electromagnet 12V', 'Actuators', 'Lifting electromagnet 12V', 8.00, 'USD', true, 80, 'Generic', 'EM-12V', '{"force": "25kg", "voltage": "12V"}', ARRAY['electromagnet', 'magnet'], '{"width": 27, "height": 21, "unit": "mm"}', 12.0, 12.0, 500.0, 'DC', 2, 'Magnet'),
('Linear Actuator Mini', 'Actuators', 'Mini linear actuator 50mm stroke', 20.00, 'USD', true, 50, 'Generic', 'LA-50MM', '{"stroke": "50mm", "force": "10N"}', ARRAY['linear', 'actuator'], '{"width": 16, "height": 90, "unit": "mm"}', 6.0, 12.0, 350.0, 'DC', 2, 'Actuator');

-- COMMUNICATION MODULES (10 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('HC-05 Bluetooth Module', 'Communication', 'Bluetooth 2.0 serial communication', 7.00, 'USD', true, 180, 'Generic', 'HC-05', '{"version": "2.0", "range": "10 meters"}', ARRAY['bluetooth', 'serial'], '{"width": 28, "height": 15, "unit": "mm"}', 3.6, 6.0, 40.0, 'Serial', 6, 'Module'),
('nRF24L01 Wireless', 'Communication', '2.4GHz wireless transceiver', 5.00, 'USD', true, 150, 'Nordic', 'nRF24L01', '{"frequency": "2.4GHz", "range": "100 meters"}', ARRAY['wireless', 'rf'], '{"width": 29, "height": 15, "unit": "mm"}', 1.9, 3.6, 13.5, 'SPI', 8, 'Module'),
('SIM800L GSM Module', 'Communication', 'GSM/GPRS cellular module', 12.00, 'USD', true, 70, 'SIMCom', 'SIM800L', '{"bands": "quad-band", "gprs": "yes"}', ARRAY['gsm', 'cellular', 'gprs'], '{"width": 22, "height": 22, "unit": "mm"}', 3.7, 4.2, 500.0, 'Serial', 12, 'Module'),
('LoRa SX1278 Module', 'Communication', 'Long range wireless LoRa transceiver', 15.00, 'USD', true, 90, 'Semtech', 'SX1278', '{"range": "5km", "frequency": "433MHz"}', ARRAY['lora', 'wireless', 'long-range'], '{"width": 16, "height": 16, "unit": "mm"}', 1.8, 3.7, 120.0, 'SPI', 16, 'Module'),
('ESP-01 WiFi Module', 'Communication', 'Compact ESP8266 WiFi module', 3.00, 'USD', true, 200, 'Espressif', 'ESP-01', '{"wifi": "802.11 b/g/n"}', ARRAY['wifi', 'esp8266'], '{"width": 14.3, "height": 24.8, "unit": "mm"}', 3.0, 3.6, 215.0, 'Serial', 8, 'Module'),
('HC-12 Wireless Serial', 'Communication', '433MHz long range serial module', 8.00, 'USD', true, 100, 'Generic', 'HC-12', '{"frequency": "433MHz", "range": "1800m"}', ARRAY['wireless', 'serial', 'long-range'], '{"width": 27.8, "height": 13.2, "unit": "mm"}', 3.2, 5.5, 100.0, 'Serial', 9, 'Module'),
('RFID RC522', 'Communication', '13.56MHz RFID reader/writer', 5.00, 'USD', true, 150, 'NXP', 'MFRC522', '{"frequency": "13.56MHz", "protocol": "ISO 14443A"}', ARRAY['rfid', 'nfc'], '{"width": 40, "height": 60, "unit": "mm"}', 2.5, 3.3, 13.0, 'SPI', 8, 'Module'),
('433MHz Transmitter', 'Communication', 'RF transmitter module 433MHz', 2.00, 'USD', true, 180, 'Generic', 'FS1000A', '{"frequency": "433MHz", "power": "10mW"}', ARRAY['rf', 'transmitter'], '{"width": 19, "height": 19, "unit": "mm"}', 3.5, 12.0, 40.0, 'Digital', 3, 'Module'),
('433MHz Receiver', 'Communication', 'RF receiver module 433MHz', 2.00, 'USD', true, 180, 'Generic', 'XY-MK-5V', '{"frequency": "433MHz", "sensitivity": "-105dBm"}', ARRAY['rf', 'receiver'], '{"width": 30, "height": 14, "unit": "mm"}', 5.0, 5.0, 4.0, 'Digital', 4, 'Module'),
('IR Transmitter Receiver', 'Communication', 'Infrared transmitter and receiver pair', 1.50, 'USD', true, 250, 'Generic', 'IR-LED', '{"wavelength": "940nm", "range": "10 meters"}', ARRAY['infrared', 'ir', 'remote'], '{"width": 5, "height": 8, "unit": "mm"}', 3.3, 5.0, 20.0, 'Digital', 2, 'Component');

-- POWER MANAGEMENT (10 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('LM2596 Buck Converter', 'Power Management', 'Step-down voltage regulator DC-DC', 3.50, 'USD', true, 200, 'Texas Instruments', 'LM2596', '{"input": "4-40V", "output": "1.25-37V", "current": "3A"}', ARRAY['buck', 'voltage-regulator'], '{"width": 43, "height": 21, "unit": "mm"}', 4.0, 40.0, 3000.0, 'DC', 2, 'Module'),
('MT3608 Boost Converter', 'Power Management', 'Step-up voltage regulator 2A', 2.50, 'USD', true, 180, 'Generic', 'MT3608', '{"input": "2-24V", "output": "5-28V", "current": "2A"}', ARRAY['boost', 'step-up'], '{"width": 37, "height": 17, "unit": "mm"}', 2.0, 24.0, 2000.0, 'DC', 2, 'Module'),
('AMS1117 3.3V Regulator', 'Power Management', 'Linear voltage regulator 3.3V 1A', 1.00, 'USD', true, 300, 'Advanced Monolithic', 'AMS1117', '{"output": "3.3V", "current": "1A"}', ARRAY['linear', 'regulator', '3.3v'], '{"width": 15, "height": 10, "unit": "mm"}', 4.75, 15.0, 1000.0, 'DC', 3, 'Component'),
('7805 Voltage Regulator', 'Power Management', 'Linear voltage regulator 5V 1.5A', 0.80, 'USD', true, 350, 'Generic', '7805', '{"output": "5V", "current": "1.5A"}', ARRAY['linear', 'regulator', '5v'], '{"width": 10, "height": 16, "unit": "mm"}', 7.0, 35.0, 1500.0, 'DC', 3, 'Component'),
('TP4056 Li-ion Charger', 'Power Management', 'Lithium battery charger module', 2.00, 'USD', true, 220, 'Generic', 'TP4056', '{"battery": "Li-ion", "current": "1A", "protection": "yes"}', ARRAY['battery', 'charger', 'lithium'], '{"width": 26, "height": 17, "unit": "mm"}', 4.5, 8.0, 1000.0, 'DC', 2, 'Module'),
('18650 Battery Holder', 'Power Management', 'Holder for 18650 lithium battery', 1.50, 'USD', true, 200, 'Generic', 'BH-18650', '{"batteries": "1", "type": "18650"}', ARRAY['battery', 'holder'], '{"width": 20, "height": 75, "unit": "mm"}', 3.7, 4.2, 0.0, 'DC', 2, 'Holder'),
('XL6009 Boost Converter', 'Power Management', 'Adjustable boost converter 4A', 4.00, 'USD', true, 150, 'Generic', 'XL6009', '{"input": "3-32V", "output": "5-35V", "current": "4A"}', ARRAY['boost', 'step-up'], '{"width": 54, "height": 23, "unit": "mm"}', 3.0, 32.0, 4000.0, 'DC', 2, 'Module'),
('Power Supply Module 5V', 'Power Management', 'AC-DC 5V 2A power supply', 5.00, 'USD', true, 120, 'Generic', 'HLK-PM01', '{"input": "100-240VAC", "output": "5V 2A"}', ARRAY['power-supply', 'ac-dc'], '{"width": 34, "height": 20, "unit": "mm"}', 100.0, 240.0, 2000.0, 'AC/DC', 3, 'Module'),
('USB Type-C PD Module', 'Power Management', 'USB-C power delivery trigger', 6.00, 'USD', true, 100, 'Generic', 'PD-USBC', '{"voltage": "5V/9V/12V/15V/20V", "protocol": "PD 3.0"}', ARRAY['usb-c', 'power-delivery'], '{"width': 25, "height": 12, "unit": "mm"}', 5.0, 20.0, 3000.0, 'USB', 2, 'Module'),
('Solar Panel 6V 1W', 'Power Management', 'Small solar panel for charging', 8.00, 'USD', true, 90, 'Generic', 'SOLAR-6V-1W', '{"voltage": "6V", "power": "1W"}', ARRAY['solar', 'renewable'], '{"width": 110, "height": 60, "unit": "mm"}', 6.0, 6.0, 167.0, 'DC', 2, 'Panel');

-- MISCELLANEOUS (5 items)
INSERT INTO public.components (name, category, description, price, currency, in_stock, stock_count, manufacturer, model_number, specifications, tags, dimensions, operating_voltage_min, operating_voltage_max, operating_current, interface_type, pin_count, package_type) VALUES
('Buzzer 5V Active', 'Audio', 'Active piezo buzzer 5V', 1.00, 'USD', true, 300, 'Generic', 'TMB12A05', '{"frequency": "2300Hz", "sound": "85dB"}', ARRAY['buzzer', 'audio'], '{"width": 12, "height": 9.5, "unit": "mm"}', 4.0, 8.0, 30.0, 'Digital', 2, 'Component'),
('Passive Buzzer', 'Audio', 'Passive piezo buzzer for tones', 0.80, 'USD', true, 350, 'Generic', 'PASSIVE-5V', '{"frequency": "2kHz-5kHz", "voltage": "3-12V"}', ARRAY['buzzer', 'audio', 'tone'], '{"width": 12, "height": 9.5, "unit": "mm"}', 3.0, 12.0, 25.0, 'PWM', 2, 'Component'),
('Breadboard 830 Points', 'Prototyping', 'Solderless breadboard for prototyping', 4.00, 'USD', true, 200, 'Generic', 'BB-830', '{"points": "830", "size": "standard"}', ARRAY['breadboard', 'prototyping'], '{"width": 165, "height": 55, "unit": "mm"}', 0.0, 0.0, 0.0, 'None', 0, 'Board'),
('Jumper Wires Set', 'Prototyping', 'Male-to-male jumper wires (40pcs)', 3.00, 'USD', true, 250, 'Generic', 'JW-MM-40', '{"quantity": "40", "length": "20cm"}', ARRAY['jumper', 'wires', 'prototyping'], '{"width": 0.1, "height": 200, "unit": "mm"}', 0.0, 0.0, 0.0, 'None', 0, 'Wire'),
('Real Time Clock DS3231', 'Timing', 'High precision RTC module with battery', 5.00, 'USD', true, 130, 'Maxim', 'DS3231', '{"accuracy": "±2ppm", "battery": "CR2032"}', ARRAY['rtc', 'clock', 'time'], '{"width": 38, "height": 22, "unit": "mm"}', 2.3, 5.5, 0.2, 'I2C', 6, 'Module');

-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================

-- Function to get component details with related data
CREATE OR REPLACE FUNCTION get_component_details(component_uuid UUID)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_build_object(
        'component', row_to_json(c),
        'reviews', COALESCE(reviews.reviews, '[]'::json),
        'projects', COALESCE(projects.projects, '[]'::json),
        'stats', json_build_object(
            'average_rating', COALESCE(AVG(r.rating), 0),
            'review_count', COUNT(DISTINCT r.id),
            'project_count', COUNT(DISTINCT p.id)
        )
    ) INTO result
    FROM public.components c
    LEFT JOIN public.component_reviews r ON c.id = r.component_id
    LEFT JOIN public.component_projects p ON c.id = p.component_id
    LEFT JOIN LATERAL (
        SELECT json_agg(row_to_json(rev)) as reviews
        FROM public.component_reviews rev
        WHERE rev.component_id = c.id
    ) reviews ON true
    LEFT JOIN LATERAL (
        SELECT json_agg(row_to_json(proj)) as projects
        FROM public.component_projects proj
        WHERE proj.component_id = c.id
    ) projects ON true
    WHERE c.id = component_uuid
    GROUP BY c.id, reviews.reviews, projects.projects;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Function to get user's projects with stats
CREATE OR REPLACE FUNCTION get_user_projects(user_guest_id VARCHAR)
RETURNS JSON AS $$
DECLARE
    result JSON;
    user_uuid UUID;
BEGIN
    -- Get user UUID from guest_id
    SELECT id INTO user_uuid FROM public.users WHERE guest_id = user_guest_id;
    
    IF user_uuid IS NULL THEN
        RETURN '[]'::json;
    END IF;
    
    SELECT json_agg(
        json_build_object(
            'project', row_to_json(p),
            'chat_count', (
                SELECT COUNT(*) FROM public.chat_messages 
                WHERE project_id = p.id
            )
        ) ORDER BY p.created_at DESC
    ) INTO result
    FROM public.projects p
    WHERE p.user_id = user_uuid;
    
    RETURN COALESCE(result, '[]'::json);
END;
$$ LANGUAGE plpgsql;

-- Function to get project chat history
CREATE OR REPLACE FUNCTION get_project_chat_history(
    project_uuid UUID,
    message_limit INTEGER DEFAULT 100
)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_agg(
        row_to_json(cm) ORDER BY cm.created_at ASC
    ) INTO result
    FROM (
        SELECT * FROM public.chat_messages
        WHERE project_id = project_uuid
        ORDER BY created_at DESC
        LIMIT message_limit
    ) cm;
    
    RETURN COALESCE(result, '[]'::json);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

-- ============================================================================
-- COMPLETION MESSAGE
-- ============================================================================
DO $$
BEGIN
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'STEM IDEA GENERATOR - DATABASE SCHEMA CREATED SUCCESSFULLY';
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'Tables created:';
    RAISE NOTICE '  - users (guest user management)';
    RAISE NOTICE '  - components (100 electronics components)';
    RAISE NOTICE '  - projects (AI-generated project ideas)';
    RAISE NOTICE '  - chat_messages (AI guidance conversations)';
    RAISE NOTICE '  - component_reviews (component reviews)';
    RAISE NOTICE '  - component_projects (example projects)';
    RAISE NOTICE '';
    RAISE NOTICE 'Total components inserted: 100';
    RAISE NOTICE 'Indexes created: Optimized for queries';
    RAISE NOTICE 'RLS policies: Enabled with public access for guest users';
    RAISE NOTICE '';
    RAISE NOTICE 'Next steps:';
    RAISE NOTICE '  1. Configure your Supabase URL and anon key in .env';
    RAISE NOTICE '  2. Update backend to use Supabase client';
    RAISE NOTICE '  3. Update frontend services to use Supabase';
    RAISE NOTICE '============================================================================';
END $$;

COMMIT;
